-- BUILT FILE - do not edit. Generated by tools/build.js from src/ and lib/;
-- edit those and run `npm run build`. `npm test` fails while this file is stale.

plugin = {
  id = "textdungeon-hud",
  name = "textdungeon-hud",
  version = "0.1.0",
  author = "wccrawford",
  description = "TextDungeon's Status, Effects and Slots as MudForge widgets, fed by the GMCP Feed.",
  settings = { saveState = true },
}

local __libs = {}
local function __require(name)
  local m = __libs[name]
  if m == nil then error("module '" .. name .. "' not found") end
  return m
end

-- lib/countdown.lua
__libs["countdown"] = (function()
  local require = __require
-- Countdown: a widget-side clock that drains toward an instant the Feed named.
-- Pure Lua 5.1 library: no globals, no clock (`now` is always an argument),
-- library-sandbox stdlib only (no Lua patterns, no string.format widths).
--
-- A Countdown is `{ ends_at = ms, span = ms }` on the caller's clock, or nil
-- when Clear. Policy (CONTEXT.md, wayfinder #7): anchor at arrival, 100 ms
-- dead-band, a Stack refills the Span, local Clear is authoritative.
local M = {}

M.DEAD_BAND_MS = 100

-- Apply a push carrying `remaining` ms (already `end - now_ms` from the Feed's
-- own clock). Returns the Countdown to keep. A push of nothing left clears.
function M.push(cd, remaining, now)
  if remaining == nil or remaining <= 0 then return nil end
  local ends_at = now + remaining
  if cd ~= nil and cd.ends_at > now then
    local delta = ends_at - cd.ends_at
    if delta >= -M.DEAD_BAND_MS and delta <= M.DEAD_BAND_MS then return cd end
    -- A Stack (lengthened) refills the bar; a shortening keeps the Span.
    local span = cd.span
    if delta > 0 then span = remaining end
    return { ends_at = ends_at, span = span }
  end
  return { ends_at = ends_at, span = remaining }
end

-- Advance the local clock: nil once the Countdown has reached Clear.
function M.tick(cd, now)
  if cd == nil or cd.ends_at <= now then return nil end
  return cd
end

-- Milliseconds left, never negative; 0 when nil.
function M.remaining(cd, now)
  if cd == nil then return 0 end
  local left = cd.ends_at - now
  if left < 0 then left = 0 end
  return left
end

-- Whole seconds, rounded up: reads `1` until the instant of Clear, never `0`.
function M.seconds(cd, now)
  return math.ceil(M.remaining(cd, now) / 1000)
end

-- Fill percentage of a draining bar (0..100, one decimal).
function M.pct(cd, now)
  if cd == nil or cd.span <= 0 then return 0 end
  local p = M.remaining(cd, now) / cd.span * 100
  if p > 100 then p = 100 end
  return math.floor(p * 10 + 0.5) / 10
end

local function pad2(n)
  if n < 10 then return "0" .. n end
  return "" .. n
end

-- Whole seconds -> "mm:ss". Negative counts as zero.
function M.mmss(seconds)
  if seconds < 0 then seconds = 0 end
  seconds = math.floor(seconds)
  local m = math.floor(seconds / 60)
  return pad2(m) .. ":" .. pad2(seconds - m * 60)
end

return M
end)()

-- lib/status.lua
__libs["status"] = (function()
  local require = __require
-- Status: the view-model behind the Status widget (Condition / Focus /
-- Footing meters, Round Time bar, Standing + Encumbrance + held power).
-- Pure Lua 5.1 library: the wiring owns a state table from `new()`, feeds it
-- Feed snapshots and the local clock, and pushes `keys()` through
-- setBoundValues. Widget states are Unfed / Live / Severed (CONTEXT.md).
local countdown = require("countdown")

local M = {}

function M.new()
  return { state = "unfed", vitals = nil, rt = nil, frozen_at = nil }
end

-- Char.Vitals snapshot: the widget goes Live on its own package's first push.
function M.vitals(s, pkg)
  if pkg == nil then return s end
  s.vitals = pkg
  s.state = "live"
  return s
end

-- Char.RoundTime snapshot: `0` or an instant already passed means clear.
function M.roundtime(s, pkg, now)
  if pkg == nil then return s end
  local remaining = 0
  if pkg.clears_at_ms ~= nil and pkg.clears_at_ms ~= 0 then
    remaining = pkg.clears_at_ms - (pkg.now_ms or 0)
  end
  s.rt = countdown.push(s.rt, remaining, now)
  return s
end

-- The local tick; returns true when the Round Time just reached Clear so the
-- caller knows the bar must be pushed one last time.
function M.tick(s, now)
  if s.state == "severed" then return false end
  local had = s.rt ~= nil
  s.rt = countdown.tick(s.rt, now)
  return had and s.rt == nil
end

-- Connection lost: keep the last-known values, freeze the Countdown here.
function M.sever(s, now)
  if s.state == "live" then
    s.state = "severed"
    s.frozen_at = now
  end
  return s
end

local function pct(cur, max)
  if cur == nil or max == nil or max <= 0 then return 0 end
  local p = cur / max * 100
  if p < 0 then p = 0 elseif p > 100 then p = 100 end
  return math.floor(p * 10 + 0.5) / 10
end

local function meter(k, key, m)
  if m == nil then
    k[key .. "Name"] = ""
    k[key .. "Cur"] = ""
    k[key .. "Max"] = ""
    k[key .. "Tier"] = ""
    k[key .. "Pct"] = "0%"
    k[key .. "Tip"] = ""
    return
  end
  k[key .. "Name"] = m.name or ""
  k[key .. "Cur"] = m.cur == nil and "" or m.cur
  k[key .. "Max"] = m.max == nil and "" or m.max
  k[key .. "Tier"] = m.tier == nil and "" or m.tier
  k[key .. "Pct"] = pct(m.cur, m.max) .. "%"
  k[key .. "Tip"] = tostring(m.cur) .. "/" .. tostring(m.max)
end

-- The complete bound-value key set for the Status widget's markup.
function M.keys(s, now)
  local k = { hudState = s.state }
  local v = s.vitals or {}
  meter(k, "cond", v.condition)
  meter(k, "focus", v.focus)
  meter(k, "foot", v.footing)
  if v.power ~= nil then
    k.powerName = v.power.name or ""
    k.powerCur = v.power.cur == nil and "" or v.power.cur
    k.powerTier = v.power.tier == nil and "" or v.power.tier
    k.powerDisplay = ""
  else
    k.powerName = ""
    k.powerCur = ""
    k.powerTier = ""
    k.powerDisplay = "none"
  end
  k.standName = v.standing and v.standing.name or ""
  k.encum = v.encumbrance == nil and "" or v.encumbrance

  if s.state == "severed" and s.frozen_at ~= nil then now = s.frozen_at end
  local cd = countdown.tick(s.rt, now)
  if cd ~= nil then
    k.rtDisplay = ""
    k.rtPct = countdown.pct(cd, now) .. "%"
    k.rtSec = countdown.seconds(cd, now)
  else
    k.rtDisplay = "none"
    k.rtPct = "0%"
    k.rtSec = ""
  end
  return k
end

return M
end)()

-- lib/effects.lua
__libs["effects"] = (function()
  local require = __require
-- Effects: the view-model behind the Effects widget (Active Effects as timer
-- rows, soonest first). Pure Lua 5.1 library, same shape as status.lua: the
-- wiring owns a state table from `new()`, feeds it Char.Effects snapshots and
-- the local clock, and pushes `keys()` through setBoundValues. Each effect
-- runs its own Countdown (CONTEXT.md); the markup is a fixed pool of POOL
-- rows flipped by bound values, never rebuilt (wayfinder #6).
local countdown = require("countdown")

local M = {}

M.POOL = 10                -- rows in the markup; beyond that only "+N more"
M.URGENT_MS = 5000         -- time and hairline turn red under this

function M.new()
  return { state = "unfed", by_name = {}, frozen_at = nil }
end

-- Char.Effects snapshot: `{ effects = { {name, ends_at_ms}, ... }, now_ms }`.
-- Walks the array with ipairs (feed arrays reach Lua 0-based under t[i]).
-- An Effect's Span is the longest remaining ever seen for its name while it
-- ran, so a re-push that lengthens it beyond the dead-band refills toward
-- that, not to the new remaining as a Round Time Stack would.
function M.effects(s, pkg, now)
  if pkg == nil then return s end
  local next_by_name = {}
  local now_ms = pkg.now_ms or 0
  for _, e in ipairs(pkg.effects or {}) do
    if e.name ~= nil and e.ends_at_ms ~= nil then
      local prev = s.by_name[e.name]
      local cd = countdown.push(prev, e.ends_at_ms - now_ms, now)
      if cd ~= nil and prev ~= nil and cd ~= prev and prev.span > cd.span then
        cd = { ends_at = cd.ends_at, span = prev.span }
      end
      if cd ~= nil then next_by_name[e.name] = cd end
    end
  end
  s.by_name = next_by_name
  s.state = "live"
  return s
end

-- The local tick; returns true when any Effect just reached Clear so the
-- caller knows its row must be pushed away.
function M.tick(s, now)
  if s.state == "severed" then return false end
  local cleared = false
  for name, cd in pairs(s.by_name) do
    if countdown.tick(cd, now) == nil then
      s.by_name[name] = nil
      cleared = true
    end
  end
  return cleared
end

-- True while any Effect is running, i.e. the tick has rows to drain.
-- (`next` is not in MudForge's sandbox; pairs is.)
function M.counting(s)
  for _ in pairs(s.by_name) do return true end
  return false
end

-- Connection lost: keep the rows, freeze every Countdown here.
function M.sever(s, now)
  if s.state == "live" then
    s.state = "severed"
    s.frozen_at = now
  end
  return s
end

-- Running Effects soonest first (name breaks ties so the order is stable).
local function sorted(s, now)
  local list = {}
  for name, cd in pairs(s.by_name) do
    if countdown.tick(cd, now) ~= nil then
      list[#list + 1] = { name = name, cd = cd }
    end
  end
  table.sort(list, function(a, b)
    if a.cd.ends_at ~= b.cd.ends_at then return a.cd.ends_at < b.cd.ends_at end
    return a.name < b.name
  end)
  return list
end

-- The complete bound-value key set for the Effects widget's markup:
-- hudState, effEmpty, effMore, and e<i>n / e<i>t / e<i>u / e<i>p / e<i>d
-- (name, mm:ss, urgency flag, hairline width, row display) for each pool row.
function M.keys(s, now)
  if s.state == "severed" and s.frozen_at ~= nil then now = s.frozen_at end
  local k = { hudState = s.state }
  local list = sorted(s, now)
  k.effEmpty = (s.state ~= "unfed" and #list == 0) and "" or "none"
  k.effMore = (#list > M.POOL) and ("+" .. (#list - M.POOL) .. " more") or ""
  for i = 1, M.POOL do
    local p = "e" .. i
    local e = list[i]
    if e ~= nil then
      local left = countdown.remaining(e.cd, now)
      k[p .. "n"] = e.name
      k[p .. "t"] = countdown.mmss(countdown.seconds(e.cd, now))
      k[p .. "u"] = (left < M.URGENT_MS) and 1 or 0
      k[p .. "p"] = countdown.pct(e.cd, now) .. "%"
      k[p .. "d"] = ""
    else
      k[p .. "n"] = ""
      k[p .. "t"] = ""
      k[p .. "u"] = 0
      k[p .. "p"] = "0%"
      k[p .. "d"] = "none"
    end
  end
  return k
end

return M
end)()

-- src/widgets/*.html, each with shared.css inlined
__libs["widgets"] = {
  ["status"] = [==[
<style>
/* Inlined into every widget by tools/build.js as a <style> block ahead of its html. */
html,body{margin:0;padding:0;background:transparent;color:#c9d1d9;font:13px/1.25 "Segoe UI",system-ui,sans-serif;overflow:hidden}
*{box-sizing:border-box}
/* tier ramp: 1 best … 5 worst (Condition / Footing / Focus), red-first like the built-in gauge;
   power 1 strongest … 4 slightest */
[data-tier="1"]{--c:#3fb950}[data-tier="2"]{--c:#d4c33a}[data-tier="3"]{--c:#f0883e}[data-tier="4"]{--c:#f25c3c}[data-tier="5"]{--c:#e5232b}
[data-ptier="1"]{--p:#c084fc}[data-ptier="2"]{--p:#a78bfa}[data-ptier="3"]{--p:#8b7cf6}[data-ptier="4"]{--p:#6e6ad6}
.rtc{--rt:#58a6ff}
/* widget states (CONTEXT.md): Unfed and Severed share one dimmed treatment; Live is full strength */
.hud{transition:opacity .2s}
.hud[data-state="unfed"],.hud[data-state="severed"]{opacity:.45}
/* Countdown urgency (Effects): 0 normal, 1 under 5 s */
[data-urg="0"]{--u:#58a6ff}[data-urg="1"]{--u:#e5232b}
</style>
<!-- Status widget: variant A "Stacked meters" from wayfinder #5. Content is set once;
     every value below is a bound key from lib/status.lua's keys(). Defaults are the
     Unfed skeleton so the widget is right before any push lands. -->
<style>
  .hud{display:flex;flex-direction:column;gap:5px;padding:2px 0}
  .row{display:grid;grid-template-columns:66px 1fr 52px;align-items:center;gap:6px}
  .lbl{color:#8b949e;font-size:12px}
  .bar{position:relative;height:18px;background:#0d1117;border:1px solid #30363d;border-radius:3px;overflow:hidden}
  .fill{position:absolute;top:0;bottom:0;left:0;background:var(--c,#555);transition:width .25s}
  .word{position:absolute;inset:0;display:flex;align-items:center;padding-left:6px;font-size:12px;color:#fff;text-shadow:0 0 3px #000,0 0 2px #000;white-space:nowrap}
  .num{color:#8b949e;font-size:12px;text-align:right;font-variant-numeric:tabular-nums}
  .rt{position:relative;height:16px;background:#0d1117;border:1px solid #30363d;border-radius:3px;overflow:hidden;margin-top:2px}
  .rtfill{position:absolute;top:0;bottom:0;left:0;background:var(--rt);transition:width .1s linear}
  .rtsec{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;font-size:12px;color:#fff;text-shadow:0 0 3px #000}
  .foot{display:flex;flex-direction:column;gap:1px;font-size:12px;color:#8b949e;margin-top:2px;white-space:nowrap}
  .foot .l{display:flex;justify-content:space-between}
  .pw{color:var(--p)}
</style>
<div class="hud hud-status" data-state="unfed" data-mud-bind-attr="data-state:hudState">
  <div class="row"><span class="lbl">Condition</span>
    <div class="bar" data-mud-bind-attr="title:condTip"><div class="fill" data-mud-bind-attr="data-tier:condTier" data-mud-bind-style="width:condPct"></div><span class="word" data-mud-bind="condName"></span></div>
    <span class="num"><span data-mud-bind="condCur"></span>/<span data-mud-bind="condMax"></span></span></div>
  <div class="row"><span class="lbl">Focus</span>
    <div class="bar" data-mud-bind-attr="title:focusTip"><div class="fill" data-mud-bind-attr="data-tier:focusTier" data-mud-bind-style="width:focusPct"></div><span class="word" data-mud-bind="focusName"></span></div>
    <span class="num"><span data-mud-bind="focusCur"></span>/<span data-mud-bind="focusMax"></span></span></div>
  <div class="row"><span class="lbl">Footing</span>
    <div class="bar" data-mud-bind-attr="title:footTip"><div class="fill" data-mud-bind-attr="data-tier:footTier" data-mud-bind-style="width:footPct"></div><span class="word" data-mud-bind="footName"></span></div>
    <span class="num"><span data-mud-bind="footCur"></span>/<span data-mud-bind="footMax"></span></span></div>
  <div class="rt rtc" style="display:none" data-mud-bind-style="display:rtDisplay"><div class="rtfill" data-mud-bind-style="width:rtPct"></div><span class="rtsec" data-mud-bind="rtSec"></span></div>
  <div class="foot">
    <div class="l"><span title="Standing" data-mud-bind="standName"></span><span>Enc <span data-mud-bind="encum"></span>%</span></div>
    <div class="pw" style="display:none" data-mud-bind-attr="data-ptier:powerTier" data-mud-bind-style="display:powerDisplay">Holding <span data-mud-bind="powerName"></span> (<span data-mud-bind="powerCur"></span>)</div>
  </div>
</div>
]==],
  ["effects"] = [==[
<style>
/* Inlined into every widget by tools/build.js as a <style> block ahead of its html. */
html,body{margin:0;padding:0;background:transparent;color:#c9d1d9;font:13px/1.25 "Segoe UI",system-ui,sans-serif;overflow:hidden}
*{box-sizing:border-box}
/* tier ramp: 1 best … 5 worst (Condition / Footing / Focus), red-first like the built-in gauge;
   power 1 strongest … 4 slightest */
[data-tier="1"]{--c:#3fb950}[data-tier="2"]{--c:#d4c33a}[data-tier="3"]{--c:#f0883e}[data-tier="4"]{--c:#f25c3c}[data-tier="5"]{--c:#e5232b}
[data-ptier="1"]{--p:#c084fc}[data-ptier="2"]{--p:#a78bfa}[data-ptier="3"]{--p:#8b7cf6}[data-ptier="4"]{--p:#6e6ad6}
.rtc{--rt:#58a6ff}
/* widget states (CONTEXT.md): Unfed and Severed share one dimmed treatment; Live is full strength */
.hud{transition:opacity .2s}
.hud[data-state="unfed"],.hud[data-state="severed"]{opacity:.45}
/* Countdown urgency (Effects): 0 normal, 1 under 5 s */
[data-urg="0"]{--u:#58a6ff}[data-urg="1"]{--u:#e5232b}
</style>
<!-- Effects widget: variant A "Timer rows" from wayfinder #6. Content is set once;
     the list is a fixed pool of 10 rows flipped by bound keys from lib/effects.lua's
     keys() — a row past the pool shows only as "+N more". Defaults are the Unfed
     skeleton: every row hidden, the "No effects" line too. -->
<style>
  /* the pool can outgrow the widget: scroll it rather than clip "+N more" */
  html,body{height:100%}
  .hud{display:flex;flex-direction:column;gap:5px;padding:2px 4px 2px 0;height:100%;overflow-y:auto;scrollbar-width:thin;scrollbar-color:#30363d transparent}
  .e,.empty{flex-shrink:0}
  .e{display:flex;flex-direction:column;gap:2px}
  .e .l{display:grid;grid-template-columns:1fr auto;align-items:baseline;gap:8px}
  .e .n{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
  .e .t{color:var(--u);font-size:12px;font-weight:600;font-variant-numeric:tabular-nums}
  .e .h{height:3px;background:#30363d;border-radius:2px;overflow:hidden}
  .e .h div{height:100%;background:var(--u);transition:width .1s linear}
  .empty{color:#6e7681;font-size:12px;font-style:italic}
</style>
<div class="hud hud-effects" data-state="unfed" data-mud-bind-attr="data-state:hudState">
  <div class="empty" style="display:none" data-mud-bind-style="display:effEmpty">No effects</div>
  <div class="e" style="display:none" data-mud-bind-attr="data-urg:e1u" data-mud-bind-style="display:e1d">
    <div class="l"><span class="n" data-mud-bind="e1n"></span><span class="t" data-mud-bind="e1t"></span></div>
    <div class="h"><div data-mud-bind-style="width:e1p"></div></div>
  </div>
  <div class="e" style="display:none" data-mud-bind-attr="data-urg:e2u" data-mud-bind-style="display:e2d">
    <div class="l"><span class="n" data-mud-bind="e2n"></span><span class="t" data-mud-bind="e2t"></span></div>
    <div class="h"><div data-mud-bind-style="width:e2p"></div></div>
  </div>
  <div class="e" style="display:none" data-mud-bind-attr="data-urg:e3u" data-mud-bind-style="display:e3d">
    <div class="l"><span class="n" data-mud-bind="e3n"></span><span class="t" data-mud-bind="e3t"></span></div>
    <div class="h"><div data-mud-bind-style="width:e3p"></div></div>
  </div>
  <div class="e" style="display:none" data-mud-bind-attr="data-urg:e4u" data-mud-bind-style="display:e4d">
    <div class="l"><span class="n" data-mud-bind="e4n"></span><span class="t" data-mud-bind="e4t"></span></div>
    <div class="h"><div data-mud-bind-style="width:e4p"></div></div>
  </div>
  <div class="e" style="display:none" data-mud-bind-attr="data-urg:e5u" data-mud-bind-style="display:e5d">
    <div class="l"><span class="n" data-mud-bind="e5n"></span><span class="t" data-mud-bind="e5t"></span></div>
    <div class="h"><div data-mud-bind-style="width:e5p"></div></div>
  </div>
  <div class="e" style="display:none" data-mud-bind-attr="data-urg:e6u" data-mud-bind-style="display:e6d">
    <div class="l"><span class="n" data-mud-bind="e6n"></span><span class="t" data-mud-bind="e6t"></span></div>
    <div class="h"><div data-mud-bind-style="width:e6p"></div></div>
  </div>
  <div class="e" style="display:none" data-mud-bind-attr="data-urg:e7u" data-mud-bind-style="display:e7d">
    <div class="l"><span class="n" data-mud-bind="e7n"></span><span class="t" data-mud-bind="e7t"></span></div>
    <div class="h"><div data-mud-bind-style="width:e7p"></div></div>
  </div>
  <div class="e" style="display:none" data-mud-bind-attr="data-urg:e8u" data-mud-bind-style="display:e8d">
    <div class="l"><span class="n" data-mud-bind="e8n"></span><span class="t" data-mud-bind="e8t"></span></div>
    <div class="h"><div data-mud-bind-style="width:e8p"></div></div>
  </div>
  <div class="e" style="display:none" data-mud-bind-attr="data-urg:e9u" data-mud-bind-style="display:e9d">
    <div class="l"><span class="n" data-mud-bind="e9n"></span><span class="t" data-mud-bind="e9t"></span></div>
    <div class="h"><div data-mud-bind-style="width:e9p"></div></div>
  </div>
  <div class="e" style="display:none" data-mud-bind-attr="data-urg:e10u" data-mud-bind-style="display:e10d">
    <div class="l"><span class="n" data-mud-bind="e10n"></span><span class="t" data-mud-bind="e10t"></span></div>
    <div class="h"><div data-mud-bind-style="width:e10p"></div></div>
  </div>
  <div class="empty" data-mud-bind="effMore"></div>
</div>
]==],
  ["slots"] = [==[
<style>
/* Inlined into every widget by tools/build.js as a <style> block ahead of its html. */
html,body{margin:0;padding:0;background:transparent;color:#c9d1d9;font:13px/1.25 "Segoe UI",system-ui,sans-serif;overflow:hidden}
*{box-sizing:border-box}
/* tier ramp: 1 best … 5 worst (Condition / Footing / Focus), red-first like the built-in gauge;
   power 1 strongest … 4 slightest */
[data-tier="1"]{--c:#3fb950}[data-tier="2"]{--c:#d4c33a}[data-tier="3"]{--c:#f0883e}[data-tier="4"]{--c:#f25c3c}[data-tier="5"]{--c:#e5232b}
[data-ptier="1"]{--p:#c084fc}[data-ptier="2"]{--p:#a78bfa}[data-ptier="3"]{--p:#8b7cf6}[data-ptier="4"]{--p:#6e6ad6}
.rtc{--rt:#58a6ff}
/* widget states (CONTEXT.md): Unfed and Severed share one dimmed treatment; Live is full strength */
.hud{transition:opacity .2s}
.hud[data-state="unfed"],.hud[data-state="severed"]{opacity:.45}
/* Countdown urgency (Effects): 0 normal, 1 under 5 s */
[data-urg="0"]{--u:#58a6ff}[data-urg="1"]{--u:#e5232b}
</style>
<!-- slots widget: replaced by its build ticket -->
<div class="hud hud-slots"></div>
]==],
}

local require = __require

-- src/textdungeon-hud.lua
-- TextDungeon HUD: Status / Effects / Slots widgets for MudForge, fed only by
-- TextDungeonC's GMCP Feed. This is the source; the file MudForge imports is
-- the built textdungeon-hud.lua at the repo root (ADR 0001).

local status = require("status")
local effects = require("effects")
local widgets = require("widgets")   -- { status = html, effects = html, slots = html }, built from src/widgets/

-- One top-anchored column on the right edge (wayfinder #14): Status / Effects /
-- Slots top-down, 12 px from the edge and between widgets. Heights include
-- MudForge's ~30 px title bar. Each widget ticket appends its entry here.
local COLUMN = { width = 240, edge = 12, gap = 12 }
local ORDER = {
  { name = "status", title = "Status", height = 176 },
  { name = "effects", title = "Effects", height = 164 },   -- five timer rows before scrolling
}

local TICK_MS = 100       -- the shared Countdown tick
local REPUSH_MS = 750     -- bound values pushed right after content is set are lost (#6)

local hud = {
  status = { id = nil, s = status.new() },
  effects = { id = nil, s = effects.new() },
}
local tick = nil
local repushDue = false   -- one re-push owed after init set the content

-- Create every widget in ORDER down the column. MudForge's saved placement
-- overrides these positions on later loads, so this only decides first install.
local function createColumn()
  local win = getWindowSize() or {}
  local x = (win.width or 0) - COLUMN.width - COLUMN.edge
  if x < 0 then x = 0 end
  local y = COLUMN.edge
  for _, w in ipairs(ORDER) do
    local id = createWidget({
      type = "html",
      name = w.name,
      title = w.title,
      position = { x = x, y = y },
      size = { width = COLUMN.width, height = w.height },
    })
    setWidgetProperty(id, "content", widgets[w.name])
    hud[w.name].id = id
    y = y + w.height + COLUMN.gap
  end
end

local function pushStatus(now)
  setBoundValues(hud.status.id, status.keys(hud.status.s, now))
end

local function pushEffects(now)
  setBoundValues(hud.effects.id, effects.keys(hud.effects.s, now))
end

local function pushAll()
  local now = getCurrentTime()
  pushStatus(now)
  pushEffects(now)
end

-- Each widget is pushed on every tick while it has a Countdown running,
-- including the tick that reaches Clear.
local function onTick()
  local now = getCurrentTime()
  local s = hud.status.s
  local counting = s.rt ~= nil
  status.tick(s, now)
  if counting then pushStatus(now) end
  local e = hud.effects.s
  counting = effects.counting(e)
  effects.tick(e, now)
  if counting then pushEffects(now) end
end

local function stopTick()
  if tick ~= nil and tick ~= "" then removeTimer(tick) end
  tick = nil
end

-- addTimer answers "" (and warns in the terminal) while MudForge considers
-- the session disconnected, and onConnect fires before it stops doing so.
-- Every feed push proves the session is up, so all timers start from the
-- feed handlers: the tick until it takes, and the one re-push owed after init.
local function ensureTick()
  if tick ~= nil and tick ~= "" then return end
  tick = addTimer(TICK_MS, onTick, true)
  if tick ~= "" and repushDue then
    repushDue = false
    addTimer(REPUSH_MS, pushAll, false)
  end
end

-- The attach routine (wayfinder #9), shared by init and onConnect: reset every
-- widget to Unfed; the tick follows with the first feed push.
local function attach()
  hud.status.s = status.new()
  hud.effects.s = effects.new()
  pushAll()
  stopTick()
end

function init()
  createColumn()

  onGMCPUpdate("Char.Vitals", function(pkg)
    ensureTick()
    status.vitals(hud.status.s, pkg)
    pushStatus(getCurrentTime())
  end)
  onGMCPUpdate("Char.RoundTime", function(pkg)
    ensureTick()
    local now = getCurrentTime()
    status.roundtime(hud.status.s, pkg, now)
    pushStatus(now)
  end)
  onGMCPUpdate("Char.Effects", function(pkg)
    ensureTick()
    local now = getCurrentTime()
    effects.effects(hud.effects.s, pkg, now)
    pushEffects(now)
  end)

  attach()
  repushDue = true
  -- A hot-reload mid-session gets no feed until the server is asked; any
  -- Core.Hello makes TextDungeonC re-send every package with a fresh now_ms.
  -- A real connect already gets that from the server's own DO GMCP re-push,
  -- so this is sent here only, not from onConnect (MudForge echoes every
  -- sendGMCP into the terminal).
  sendGMCP("Core.Hello", { client = plugin.id, version = plugin.version })
end

function onConnect()
  attach()
end

function onDisconnect()
  local now = getCurrentTime()
  status.sever(hud.status.s, now)
  effects.sever(hud.effects.s, now)
  pushAll()
  stopTick()
end
