-- BUILT FILE - do not edit. Generated by tools/build.js from src/ and lib/;
-- edit those and run `npm run build`. `npm test` fails while this file is stale.

plugin = {
  id = "textdungeon-hud",
  name = "textdungeon-hud",
  version = "0.1.0",
  author = "wccrawford",
  description = "TextDungeon's Status, Effects and Slots as MudForge widgets, fed by the GMCP Feed.",
  settings = { saveState = true },
}

local __libs = {}
local function __require(name)
  local m = __libs[name]
  if m == nil then error("module '" .. name .. "' not found") end
  return m
end

-- lib/countdown.lua
__libs["countdown"] = (function()
  local require = __require
-- Countdown: a widget-side clock that drains toward an instant the Feed named.
-- Pure Lua 5.1 library: no globals, no clock (`now` is always an argument),
-- library-sandbox stdlib only (no Lua patterns, no string.format widths).
local M = {}

local function pad2(n)
  if n < 10 then return "0" .. n end
  return "" .. n
end

-- Whole seconds -> "mm:ss". Negative counts as zero.
function M.mmss(seconds)
  if seconds < 0 then seconds = 0 end
  seconds = math.floor(seconds)
  local m = math.floor(seconds / 60)
  return pad2(m) .. ":" .. pad2(seconds - m * 60)
end

return M
end)()

-- src/widgets/*.html, each with shared.css inlined
__libs["widgets"] = {
  ["status"] = [==[
<style>
/* Inlined into every widget by tools/build.js as a <style> block ahead of its html. */
</style>
<!-- status widget: replaced by its build ticket -->
<div class="hud hud-status"></div>
]==],
  ["effects"] = [==[
<style>
/* Inlined into every widget by tools/build.js as a <style> block ahead of its html. */
</style>
<!-- effects widget: replaced by its build ticket -->
<div class="hud hud-effects"></div>
]==],
  ["slots"] = [==[
<style>
/* Inlined into every widget by tools/build.js as a <style> block ahead of its html. */
</style>
<!-- slots widget: replaced by its build ticket -->
<div class="hud hud-slots"></div>
]==],
}

local require = __require

-- src/textdungeon-hud.lua
-- TextDungeon HUD: Status / Effects / Slots widgets for MudForge, fed only by
-- TextDungeonC's GMCP Feed. This is the source; the file MudForge imports is
-- the built textdungeon-hud.lua at the repo root (ADR 0001).

local countdown = require("countdown")
local widgets = require("widgets")   -- { status = html, effects = html, slots = html }, built from src/widgets/

function init()
end
