// PROTOTYPE build step: node prototype/map-levels/build-lua.js
// Inlines ../map-look/render.js and levels.js into map-levels-prototype.lua, a
// MudForge plugin with one html widget. The widget's script draws (throwaway); the
// level clicks go to Lua through data-mud-action, and Lua owns Browsing and pushes
// it back, so the round trip is the real window's.
const fs = require('fs');
const path = require('path');
const dir = __dirname;
const render = fs.readFileSync(path.join(dir, '..', 'map-look', 'render.js'), 'utf8');
const levels = fs.readFileSync(path.join(dir, 'levels.js'), 'utf8');

const content = `<style>
html,body{margin:0;height:100%;background:transparent;color:#c9d1d9;font:13px/1.25 "Segoe UI",system-ui,sans-serif;overflow:hidden}
*{box-sizing:border-box}
#root{display:flex;flex-direction:column;height:100%;padding:4px}
#out{flex:1;min-height:0}
#pick{display:flex;gap:4px;align-items:center;font-size:11px;color:#8b949e;padding-top:3px;border-top:1px dashed #30363d;margin-top:3px}
#pick button{background:#161b22;color:#c9d1d9;border:1px solid #30363d;border-radius:3px;font:inherit;padding:0 6px;cursor:pointer}
#pick button.on{background:#ffd33d;color:#000}
</style>
<div id="root"><div id="out"></div>
<div id="pick">PROTOTYPE <button data-v="E">E Markers</button><button data-v="F">F Counts</button><button data-v="A">A Stepper</button><button data-v="B">B Chips</button><button data-v="C">C Ladder</button><button data-v="D">D Stairs</button></div></div>
<script>
${render}
${levels}
var css=document.createElement('style');css.textContent=MapLook.CSS+'\\n'+LevelCtl.CSS;document.head.appendChild(css);
var V='E',map=null,where=null,level=null;
function reason(){ if(!map) return 'nomap'; if(!Object.keys(map.rooms||{}).length) return 'nocells';
  if(where && !where.here) return 'offplane'; return null; }
function draw(){
  var view={hud:'live',map:map,where:where&&map&&map.rooms[where.here]?where:{members:(where||{}).members||{}},level:level,reason:reason()};
  document.getElementById('out').innerHTML=MapLook.render('A',LevelCtl.view(V,view));
  [].forEach.call(document.querySelectorAll('#pick [data-v]'),function(b){b.className=b.dataset.v===V?'on':''});
}
document.getElementById('pick').addEventListener('click',function(e){
  var b=e.target.closest('button');if(!b||!b.dataset.v)return;V=b.dataset.v;mudforge.send('variant',{v:V});draw();
});
mudforge.onMessage(function(d){
  if(d.v) V=d.v;
  if('map' in d) map=d.map;
  if('where' in d) where=d.where;
  level=d.level==null?null:d.level;
  draw();
});
draw();mudforge.send('ready',{});
</script>`;
if (content.includes(']==]')) throw new Error('markup contains ]==]');

const lua = `-- PROTOTYPE — throwaway. Generated by prototype/map-levels/build-lua.js from
-- ../map-look/render.js and levels.js; edit those, not this file. One html widget,
-- "Map levels (prototype)": look A with four level controls (buttons in the widget).
-- Level clicks arrive here as widget "action" events; Lua owns Browsing.
-- Wayfinder ticket "How the player steps between levels", map #17. Nothing ships.
plugin = {
  id = "map-levels-prototype",
  name = "map-levels-prototype",
  version = "0.0.1",
  author = "wccrawford",
  description = "PROTOTYPE: level controls for the TextDungeon Map window. Throwaway.",
}

local CONTENT = [==[
${content}
]==]

local id, lastMap, lastWhere, variant, level = nil, nil, nil, "E", nil

local function myZ()
  local here = lastWhere and lastWhere.here
  local r = here and lastMap and lastMap.rooms and lastMap.rooms[here]
  return r and r.z
end

local function push()
  if not id then return end
  sendWidgetMessage(id, { v = variant, map = lastMap, where = lastWhere, level = level })
end

function init()
  id = createWidget({
    type = "html", name = "map-levels-prototype", title = "Map levels (prototype)",
    position = { x = 80, y = 80 }, size = { width = 420, height = 440 },
  })
  setWidgetProperty(id, "content", CONTENT)
  registerWidgetEvent(id, "luamsg", function(m)
    if m.event == "variant" and m.data then variant = m.data.v end
    if m.event == "ready" then push() end
  end)
  registerWidgetEvent(id, "action", function(d)
    if d.action ~= "level" then return end
    local z = (d.data ~= "mine") and tonumber(d.data) or nil
    if z == myZ() then z = nil end -- showing your own level is not Browsing
    level = z
    push()
  end)
  onGMCPUpdate("Area.Map", function(pkg)
    if not lastMap or lastMap.area ~= pkg.area then level = nil end -- another Area ends Browsing
    lastMap = pkg; push()
  end)
  onGMCPUpdate("Area.Where", function(pkg)
    if not lastWhere or lastWhere.here ~= pkg.here then level = nil end -- moving ends Browsing
    lastWhere = pkg; push()
  end)
  sendGMCP("Core.Hello", { client = "MudForge", version = "map-levels-prototype" })
end
`;
fs.writeFileSync(path.join(dir, 'map-levels-prototype.lua'), lua);
console.log('wrote map-levels-prototype.lua', lua.length, 'bytes');
