-- PROTOTYPE — throwaway. Generated by prototype/map-levels/build-lua.js from
-- ../map-look/render.js and levels.js; edit those, not this file. One html widget,
-- "Map levels (prototype)": look A with four level controls (buttons in the widget).
-- Level clicks arrive here as widget "action" events; Lua owns Browsing.
-- Wayfinder ticket "How the player steps between levels", map #17. Nothing ships.
plugin = {
  id = "map-levels-prototype",
  name = "map-levels-prototype",
  version = "0.0.1",
  author = "wccrawford",
  description = "PROTOTYPE: level controls for the TextDungeon Map window. Throwaway.",
}

local CONTENT = [==[
<style>
html,body{margin:0;height:100%;background:transparent;color:#c9d1d9;font:13px/1.25 "Segoe UI",system-ui,sans-serif;overflow:hidden}
*{box-sizing:border-box}
#root{display:flex;flex-direction:column;height:100%;padding:4px}
#out{flex:1;min-height:0}
#pick{display:flex;gap:4px;align-items:center;font-size:11px;color:#8b949e;padding-top:3px;border-top:1px dashed #30363d;margin-top:3px}
#pick button{background:#161b22;color:#c9d1d9;border:1px solid #30363d;border-radius:3px;font:inherit;padding:0 6px;cursor:pointer}
#pick button.on{background:#ffd33d;color:#000}
</style>
<div id="root"><div id="out"></div>
<div id="pick">PROTOTYPE <button data-v="E">E Markers</button><button data-v="F">F Counts</button><button data-v="A">A Stepper</button><button data-v="B">B Chips</button><button data-v="C">C Ladder</button><button data-v="D">D Stairs</button></div></div>
<script>
// PROTOTYPE — throwaway (wayfinder ticket "What the Map looks like", map #17).
// Three structurally different looks for the Map window, drawn from one Area.Map
// + Area.Where as an HTML string (header, SVG plane, holds, reason). The real
// window will draw this from the Lua lib (ticket "How the Map window redraws");
// this is JS only so the looks can be flipped in a browser and in MudForge.
//
//   MapLook.render(variant, view) -> html
//   view = { hud: 'live'|'unfed'|'severed', map, where: {here, members},
//            level (z shown, or null = the player's), reason: null|'nomap'|'nocells'|'offplane' }
(function (root) {
  var U = 20; // one cell in SVG units; Fit scales the viewBox, so this is only proportion

  var DIRS = {
    north: [0, 1], south: [0, -1], east: [1, 0], west: [-1, 0],
    northeast: [1, 1], northwest: [-1, 1], southeast: [1, -1], southwest: [-1, -1],
  };

  var TERRAIN = {
    inside: '#7d8590', city: '#a371f7', road: '#c2a878', field: '#6cae4f', forest: '#2e8b57',
    water: '#3b82c4', swamp: '#808c2e', cave: '#9a6b4f', hills: '#d29b45',
  };
  var NONE = '#3d444d';
  var YOU = '#ffd33d', GROUP = '#ff7b72', BACK = '#39c5cf', LINE = '#8b949e';

  function esc(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
  function keys(o) { return o ? Object.keys(o) : []; }

  // ---- the model every look reads ------------------------------------------------

  function levels(map) {
    var zs = {};
    keys(map.rooms).forEach(function (id) { zs[map.rooms[id].z] = true; });
    return keys(zs).map(Number).sort(function (a, b) { return a - b; });
  }

  // Level shown: the browsed one, else the player's, else 0, else the lowest (CONTEXT.md).
  function shownLevel(view) {
    var map = view.map, zs = levels(map);
    if (view.level != null && zs.indexOf(view.level) >= 0) return view.level;
    var here = view.where && view.where.here && map.rooms[view.where.here];
    if (here) return here.z;
    return zs.indexOf(0) >= 0 ? 0 : zs[0];
  }

  // Fit frames the whole Plane's x/y bounds (all levels), so the frame doesn't jump between levels.
  function bounds(map) {
    var b = { x0: Infinity, x1: -Infinity, y0: Infinity, y1: -Infinity };
    keys(map.rooms).forEach(function (id) {
      var r = map.rooms[id];
      b.x0 = Math.min(b.x0, r.x); b.x1 = Math.max(b.x1, r.x);
      b.y0 = Math.min(b.y0, r.y); b.y1 = Math.max(b.y1, r.y);
    });
    return b;
  }

  function px(r) { return r.x * U; }
  function py(r) { return -r.y * U; } // north is +y; SVG y grows down

  // Everything one level needs, worked out once: rooms, edges (paired), stubs, marks.
  function scene(view) {
    var map = view.map, z = shownLevel(view), rooms = [], edges = [], stubs = [], seen = {};
    keys(map.rooms).forEach(function (id) {
      var r = map.rooms[id];
      if (r.z !== z) return;
      var doors = r.doors || {}, up = false, down = false, upZ = null, downZ = null, odd = [];
      keys(r.exits).forEach(function (w) {
        var t = map.rooms[r.exits[w]];
        if (!t) return;
        if (t.z !== r.z) { if (t.z > r.z) { up = true; upZ = t.z; } else { down = true; downZ = t.z; } return; }
        var k = id < r.exits[w] ? id + '|' + r.exits[w] : r.exits[w] + '|' + id;
        var door = doors[w] || null;
        if (seen[k]) { if (door && !seen[k].door) seen[k].door = door; return; }
        seen[k] = { a: r, b: t, word: w, door: door, diag: t.x !== r.x && t.y !== r.y, far: Math.max(Math.abs(t.x - r.x), Math.abs(t.y - r.y)) > 1 };
        edges.push(seen[k]);
      });
      (r.leaves || []).forEach(function (w) {
        if (w === 'up') { up = up || 'leaves'; return; }
        if (w === 'down') { down = down || 'leaves'; return; }
        if (DIRS[w]) stubs.push({ r: r, word: w, kind: 'leaves', door: doors[w] || null });
        else odd.push({ word: w, kind: 'leaves', door: doors[w] || null });
      });
      (r.unexplored || []).forEach(function (w) {
        if (w === 'up') { up = up || 'unexplored'; return; }
        if (w === 'down') { down = down || 'unexplored'; return; }
        if (DIRS[w]) stubs.push({ r: r, word: w, kind: 'unexplored', door: doors[w] || null });
        else odd.push({ word: w, kind: 'unexplored' });
      });
      if (r.back) {
        if (DIRS[r.back]) stubs.push({ r: r, word: r.back, kind: 'back', door: doors[r.back] || null });
        else odd.push({ word: r.back, kind: 'back' });
      }
      rooms.push({ id: id, r: r, up: up, down: down, upZ: upZ, downZ: downZ, odd: odd });
    });
    var where = view.where || {}, members = [];
    keys(where.members).forEach(function (name) {
      var t = map.rooms[where.members[name]];
      if (t) members.push({ name: name, id: where.members[name], r: t, here: t.z === z });
    });
    var you = where.here && map.rooms[where.here];
    return {
      z: z, zs: levels(map), b: bounds(map), rooms: rooms, edges: edges, stubs: stubs,
      you: you && you.z === z ? you : null, youId: where.here, youLevel: you ? you.z : null,
      members: members,
    };
  }

  function tip(o) {
    var r = o.r, t = [r.terrain || 'no terrain'];
    if (o.up) t.push(o.up === true ? 'stairs up' : o.up === 'leaves' ? 'up leaves this map' : 'up, unexplored');
    if (o.down) t.push(o.down === true ? 'stairs down' : o.down === 'leaves' ? 'down leaves this map' : 'down, unexplored');
    keys(r.doors).forEach(function (w) { t.push(w + ': ' + r.doors[w].name + (r.doors[w].closed ? ' (closed)' : ' (open)')); });
    o.odd.forEach(function (x) { t.push(x.word + (x.kind === 'leaves' ? ' leaves this map' : x.kind === 'back' ? ' leads back out' : ', unexplored')); });
    if (r.back) t.push(r.back + ' leads back out');
    return t.join('\n');
  }

  // viewBox around the whole Plane plus room for stubs; the cell-size cap rides on max-width/height.
  function frame(s, pad, capPx) {
    var b = s.b, x = b.x0 * U - pad, y = -b.y1 * U - pad;
    var w = (b.x1 - b.x0) * U + 2 * pad, h = (b.y1 - b.y0) * U + 2 * pad;
    return '<svg class="plane" viewBox="' + x + ' ' + y + ' ' + w + ' ' + h + '" preserveAspectRatio="xMidYMid meet" ' +
      'style="max-width:' + (w / U * capPx) + 'px;max-height:' + (h / U * capPx) + 'px">';
  }

  function levelText(s) {
    if (s.zs.length < 2) return '';
    return 'Level ' + (s.zs.indexOf(s.z) + 1) + ' of ' + s.zs.length;
  }

  function reasonText(view) {
    var a = view.map && view.map.area;
    if (view.reason === 'nomap') return 'No map from the server yet. If <code>config map</code> is off, <code>config map on</code> brings it back.';
    if (view.reason === 'nocells') return esc(a || 'This Area') + ' has no map.';
    if (view.reason === 'offplane') return 'You are not on the map of ' + esc(a || 'this Area') + '.';
    return '';
  }

  function holdsList(map) {
    var h = map.holds || {}, out = [];
    if (h.enemies && h.enemies.length) out.push({ k: 'Enemies', v: h.enemies });
    if (h.gather && h.gather.length) out.push({ k: 'Gather', v: h.gather });
    return out;
  }

  function off(w, d) { var v = DIRS[w]; return [v[0] * d, -v[1] * d]; }

  // ===============================================================================
  // A — Tiles: terrain-filled squares with gaps, short bridges between them,
  // terrain also told by a fill pattern; header bar on top, holds as a footer.
  // ===============================================================================

  // Tile-local textures: every tile is drawn inside its own translate(), so a
  // userSpaceOnUse pattern starts at the tile's corner and lines up across tiles.
  // The tile is 12 units and each pattern 6, so every tile shows the same 2x2.
  var INK = 'stroke="#000" stroke-opacity=".38"', INKF = 'fill="#000" fill-opacity=".38"';
  var PAT = {
    city: '<path d="M0 .5h6M0 3.5h6M1.5 .5v3M4.5 3.5v3" fill="none" ' + INK + ' stroke-width=".8"/>',
    road: '<path d="M.5 3h2.4M3.5 3h2" fill="none" ' + INK + ' stroke-width="1.1"/>',
    field: '<circle cx="3" cy="3" r=".95" ' + INKF + '/>',
    forest: '<path d="M3 .8l2.2 3.8H.8z" ' + INKF + '/>',
    water: '<path d="M0 3q1.5-2 3 0t3 0" fill="none" stroke="#fff" stroke-opacity=".45" stroke-width=".9"/>',
    swamp: '<path d="M0 4.5q1.5-1.5 3 0t3 0M1.5 .8v2M4.5 1.2v1.6" fill="none" ' + INK + ' stroke-width=".85"/>',
    cave: '<path d="M1 2.2h1.6M3.6 4.6h1.6M.4 5.4h.8M4.2 1h1" fill="none" ' + INK + ' stroke-width="1.3" stroke-linecap="round"/>',
    hills: '<path d="M.3 4.8q2.7-4.2 5.4 0" fill="none" ' + INK + ' stroke-width=".9"/>',
  };
  // One centred motif per tile instead (variant D), drawn in the same 12-unit tile space.
  var MOTIF = {
    inside: '<rect x="2.5" y="2.5" width="7" height="7" rx="1" fill="none" ' + INK + ' stroke-width="1.1"/>',
    city: '<path d="M3 10V5.5L6 2.5L9 5.5V10z" fill="none" ' + INK + ' stroke-width="1.1"/>',
    road: '<path d="M2 4.5h8M2 7.5h8" fill="none" ' + INK + ' stroke-width="1.1"/>',
    field: '<path d="M3 9l1-3.5M6 9V4.5M9 9l-1-3.5" fill="none" ' + INK + ' stroke-width="1.1" stroke-linecap="round"/>',
    forest: '<path d="M6 2l3.4 5.6H2.6z" ' + INKF + '/><path d="M6 7.6V10" ' + INK + ' stroke-width="1.2"/>',
    water: '<path d="M1.5 4.5q1.5-2 3 0t3 0t3 0M1.5 8q1.5-2 3 0t3 0t3 0" fill="none" stroke="#fff" stroke-opacity=".55" stroke-width="1"/>',
    swamp: '<path d="M1.5 8.5q1.5-1.6 3 0t3 0t3 0M4 6.5V3M6 6.5V2.2M8 6.5V3.4" fill="none" ' + INK + ' stroke-width="1"/>',
    cave: '<path d="M2.5 10V6.5a3.5 3.5 0 0 1 7 0V10" fill="none" ' + INK + ' stroke-width="1.2"/>',
    hills: '<path d="M1 9q2.5-5 5 0M5 9q2.5-5 5 0" fill="none" ' + INK + ' stroke-width="1"/>',
  };

  function variantA(view, s, motif) {
    var T = 12, h = T / 2, g = '', EDGE = 2.6;
    var defs = '<defs>' + (motif ? '' : keys(PAT).map(function (t) {
      return '<pattern id="pA-' + t + '" width="6" height="6" patternUnits="userSpaceOnUse">' + PAT[t] + '</pattern>';
    }).join('')) +
      '<marker id="aA" viewBox="0 0 6 6" refX="2" refY="3" markerWidth="6" markerHeight="6" markerUnits="userSpaceOnUse" orient="auto"><path d="M0 0L6 3L0 6z" fill="' + LINE + '"/></marker>' +
      '<marker id="aB" viewBox="0 0 6 6" refX="2" refY="3" markerWidth="6" markerHeight="6" markerUnits="userSpaceOnUse" orient="auto"><path d="M0 0L6 3L0 6z" fill="' + BACK + '"/></marker></defs>';

    s.edges.forEach(function (e) {
      g += '<line x1="' + px(e.a) + '" y1="' + py(e.a) + '" x2="' + px(e.b) + '" y2="' + py(e.b) + '" stroke="' + LINE + '" stroke-width="' + EDGE + '"' + (e.far ? ' stroke-dasharray="3 2"' : '') + '/>';
    });
    s.stubs.forEach(function (st) {
      var o0 = off(st.word, h), o1 = off(st.word, U * 0.6), x = px(st.r), y = py(st.r);
      var col = st.kind === 'back' ? BACK : LINE;
      var dash = st.kind === 'unexplored' ? ' stroke-dasharray="2 1.6"' : '';
      var end = st.kind === 'unexplored' ? '' : ' marker-end="url(#' + (st.kind === 'back' ? 'aB' : 'aA') + ')"';
      g += '<line x1="' + (x + o0[0]) + '" y1="' + (y + o0[1]) + '" x2="' + (x + o1[0]) + '" y2="' + (y + o1[1]) + '" stroke="' + col + '" stroke-width="' + EDGE + '"' + dash + end + '/>';
      if (st.kind === 'unexplored') {
        var q = off(st.word, U * 0.6 + 3);
        g += '<circle cx="' + (x + q[0]) + '" cy="' + (y + q[1]) + '" r="3.4" fill="#0d1117" stroke="#e6edf3" stroke-width="1"/>' +
          '<text x="' + (x + q[0]) + '" y="' + (y + q[1] + 2) + '" font-size="5.4" font-weight="700" text-anchor="middle" fill="#e6edf3">?</text>';
      }
    });
    var badges = '';
    s.rooms.forEach(function (o) {
      var r = o.r, x = px(r) - h, y = py(r) - h, col = TERRAIN[r.terrain] || NONE;
      g += '<g data-id="' + esc(o.id) + '" transform="translate(' + x + ' ' + y + ')"><title>' + esc(tip(o)) + '</title>' +
        '<rect width="' + T + '" height="' + T + '" rx="2" fill="' + col + '"' + (r.terrain ? '' : ' stroke="#6e7681" stroke-width=".8"') + '/>';
      if (motif) g += MOTIF[r.terrain] || '';
      else if (r.terrain === 'inside') g += MOTIF.inside; // a room-in-a-room frame; no texture
      else if (PAT[r.terrain]) g += '<rect width="' + T + '" height="' + T + '" rx="2" fill="url(#pA-' + r.terrain + ')"/>';
      g += '</g>';
      // badges sit on the tile's corners, half outside it, drawn over everything else
      var cx = x + T, sd = 'stroke="#0d1117" stroke-width="1.2" stroke-linejoin="round"';
      function tri(cy, dir, how, toZ) {
        var d = 'M' + (cx - 3.6) + ' ' + (cy + 2.6 * dir) + 'L' + cx + ' ' + (cy - 3 * dir) + 'L' + (cx + 3.6) + ' ' + (cy + 2.6 * dir) + 'z';
        // levels prototype, variant D: a stair on this map is itself the control
        if (how === true && view.stairClick) return '<g class="stair" data-mud-action="level" data-mud-data="' + toZ + '"><title>Show level ' + (s.zs.indexOf(toZ) + 1) + '</title>' +
          '<circle cx="' + cx + '" cy="' + cy + '" r="6" fill="transparent"/><path d="' + d + '" fill="#fff" ' + sd + '/></g>';
        if (how === true) return '<path d="' + d + '" fill="#fff" ' + sd + '/>';
        // a stair that leaves this map (a Depth) or isn't explored: hollow, on a dark ground
        return '<path d="' + d + '" fill="#0d1117" stroke="#fff" stroke-width="1.2" stroke-linejoin="round"' + (how === 'unexplored' ? ' stroke-dasharray="1.6 1"' : '') + '/>';
      }
      if (o.up) badges += tri(y + 1.5, 1, o.up, o.upZ);
      if (o.down) badges += tri(y + T - 1.5, -1, o.down, o.downZ);
      if (o.odd.length) {
        var bk = o.odd.some(function (q) { return q.kind === 'back'; });
        badges += '<g><title>' + esc(o.odd.map(function (q) { return q.word; }).join(', ')) + '</title><circle cx="' + x + '" cy="' + y + '" r="3.6" fill="' + (bk ? BACK : '#fff') + '" ' + sd + '/>' +
          '<path d="M' + (x - 1.5) + ' ' + (y + 1.5) + 'L' + (x + 1.6) + ' ' + (y - 1.6) + 'M' + (x - .6) + ' ' + (y - 1.6) + 'H' + (x + 1.6) + 'V' + (y + .6) + '" fill="none" stroke="#0d1117" stroke-width="1"/></g>';
      }
    });
    // doors: a bar across the line (closed = solid across, open = two jambs)
    s.edges.concat(s.stubs).forEach(function (e) {
      if (!e.door) return;
      var a = e.a || e.r, v = DIRS[e.word] || [Math.sign(e.b.x - a.x), Math.sign(e.b.y - a.y)];
      var mx = px(a) + v[0] * U / 2, my = py(a) - v[1] * U / 2, n = Math.hypot(v[0], v[1]), nx = -v[1] / n, ny = -v[0] / n;
      var L = 4.8;
      if (e.door.closed) g += '<line x1="' + (mx - nx * L) + '" y1="' + (my - ny * L) + '" x2="' + (mx + nx * L) + '" y2="' + (my + ny * L) + '" stroke="#f0883e" stroke-width="3"><title>' + esc(e.door.name) + ' (closed)</title></line>';
      else g += '<g stroke="#f0883e" stroke-width="2.2"><title>' + esc(e.door.name) + ' (open)</title><line x1="' + (mx - nx * L) + '" y1="' + (my - ny * L) + '" x2="' + (mx - nx * 2.2) + '" y2="' + (my - ny * 2.2) + '"/><line x1="' + (mx + nx * 2.2) + '" y1="' + (my + ny * 2.2) + '" x2="' + (mx + nx * L) + '" y2="' + (my + ny * L) + '"/></g>';
    });
    s.members.forEach(function (m, i) {
      if (!m.here) return;
      var x = px(m.r) - h + i * 6, y = py(m.r) + h;
      g += '<g><title>' + esc(m.name) + '</title><circle cx="' + x + '" cy="' + y + '" r="4" fill="' + GROUP + '" stroke="#0d1117" stroke-width="1.2"/>' +
        '<text x="' + x + '" y="' + (y + 1.9) + '" font-size="5.4" text-anchor="middle" fill="#0d1117" font-weight="700">' + esc(m.name[0]) + '</text></g>';
    });
    if (s.you) g += '<rect class="you" x="' + (px(s.you) - h - 2.6) + '" y="' + (py(s.you) - h - 2.6) + '" width="' + (T + 5.2) + '" height="' + (T + 5.2) + '" rx="3.5" fill="none" stroke="' + YOU + '" stroke-width="2.4"><title>You</title></rect>' +
      '<circle cx="' + px(s.you) + '" cy="' + py(s.you) + '" r="2.8" fill="' + YOU + '" stroke="#0d1117" stroke-width="1.2"/>';
    g += badges; // over the you ring, so it never hides a mark

    // levels prototype: a variant may replace the header's level text, the away line, or add a side strip
    var lv = view.levelHtml ? view.levelHtml(s) : levelText(s), holds = holdsList(view.map), away = view.awayHtml ? view.awayHtml(s) : awayNote(s);
    return '<div class="A">' +
      '<div class="A-head"><div class="A-area">' + esc(view.map.area) + '</div>' +
      (view.map.region ? '<div class="A-region">' + esc(view.map.region) + '</div>' : '') +
      (lv ? '<div class="A-level">' + lv + '</div>' : '') + '</div>' +
      '<div class="A-body">' + frame(s, U * 0.9, 34) + defs + g + '</svg>' + (view.sideHtml ? view.sideHtml(s) : '') + '</div>' +
      (away ? '<div class="A-away">' + away + '</div>' : '') +
      (view.footHtml ? view.footHtml(s) : '') +
      (holds.length ? '<div class="A-holds">' + holds.map(function (x) { return '<div><b>' + x.k + '</b> ' + x.v.map(esc).join(', ') + '</div>'; }).join('') + '</div>' : '') +
      '</div>';
  }

  // Who is drawn on another level than the one shown (you while Browsing, members).
  function awayNote(s) {
    var t = [];
    if (s.youLevel != null && s.youLevel !== s.z) t.push('You: level ' + (s.zs.indexOf(s.youLevel) + 1));
    s.members.forEach(function (m) { if (!m.here) t.push(esc(m.name) + ': level ' + (s.zs.indexOf(m.r.z) + 1)); });
    return t.join(' · ');
  }

  // ===============================================================================
  // B — Nodes and lines: a transit diagram. Small nodes, terrain by colour AND
  // node shape, thick lines, stubs fade out; header is an overlay in the map's
  // corner, holds a side column (like the text verb's side column, not its glyphs).
  // ===============================================================================

  function shapeB(t, x, y, col) {
    var r = 4.2, p = ' fill="' + col + '" stroke="#0d1117" stroke-width="1.2"';
    switch (t) {
      case 'inside': case 'city': return '<rect x="' + (x - r) + '" y="' + (y - r) + '" width="' + 2 * r + '" height="' + 2 * r + '"' + p + '/>';
      case 'forest': case 'hills': return '<path d="M' + x + ' ' + (y - r - 1) + 'L' + (x + r + 1) + ' ' + (y + r) + 'H' + (x - r - 1) + 'z"' + p + '/>';
      case 'water': case 'swamp': return '<path d="M' + x + ' ' + (y - r - 1) + 'L' + (x + r + 1) + ' ' + y + 'L' + x + ' ' + (y + r + 1) + 'L' + (x - r - 1) + ' ' + y + 'z"' + p + '/>';
      case 'road': return '<rect x="' + (x - r - 1) + '" y="' + (y - r + 1.5) + '" width="' + (2 * r + 2) + '" height="' + (2 * r - 3) + '" rx="1.5"' + p + '/>';
      case 'cave': return '<path d="M' + (x - r) + ' ' + (y + r) + 'V' + y + 'a' + r + ' ' + r + ' 0 0 1 ' + 2 * r + ' 0V' + (y + r) + 'z"' + p + '/>';
      case undefined: return '<circle cx="' + x + '" cy="' + y + '" r="' + r + '" fill="#0d1117" stroke="#8b949e" stroke-width="1.2"/>';
      default: return '<circle cx="' + x + '" cy="' + y + '" r="' + r + '"' + p + '/>';
    }
  }

  function variantB(view, s) {
    var g = '', defs = '<defs><linearGradient id="fB" gradientUnits="objectBoundingBox"><stop offset="0" stop-color="' + LINE + '"/><stop offset="1" stop-color="' + LINE + '" stop-opacity="0"/></linearGradient></defs>';
    s.edges.forEach(function (e) {
      g += '<line x1="' + px(e.a) + '" y1="' + py(e.a) + '" x2="' + px(e.b) + '" y2="' + py(e.b) + '" stroke="#57606a" stroke-width="3" stroke-linecap="round"' + (e.far ? ' stroke-dasharray="3 3"' : '') + '/>';
    });
    s.stubs.forEach(function (st) {
      var x = px(st.r), y = py(st.r), o = off(st.word, U * 0.75);
      if (st.kind === 'unexplored') {
        g += '<line x1="' + x + '" y1="' + y + '" x2="' + (x + o[0]) + '" y2="' + (y + o[1]) + '" stroke="#57606a" stroke-width="2" stroke-dasharray="2 2.5"/>' +
          '<text x="' + (x + o[0]) + '" y="' + (y + o[1] + 2.6) + '" font-size="7.5" text-anchor="middle" fill="#8b949e" font-weight="700">?</text>';
      } else if (st.kind === 'back') {
        g += '<line x1="' + x + '" y1="' + y + '" x2="' + (x + o[0]) + '" y2="' + (y + o[1]) + '" stroke="' + BACK + '" stroke-width="3" stroke-linecap="round"/>' +
          '<circle cx="' + (x + o[0]) + '" cy="' + (y + o[1]) + '" r="2.4" fill="' + BACK + '"/>';
      } else {
        // a line that runs off and fades: the way goes on, the map doesn't
        var d = off(st.word, 1), sx = x + o[0], sy = y + o[1];
        g += '<path d="M' + x + ' ' + y + 'L' + sx + ' ' + sy + '" stroke="#57606a" stroke-width="3" stroke-linecap="butt"/>' +
          '<path d="M' + (sx + d[1] * 3) + ' ' + (sy - d[0] * 3) + 'L' + (sx + d[0] * 3) + ' ' + (sy + d[1] * 3) + 'L' + (sx - d[1] * 3) + ' ' + (sy + d[0] * 3) + '" fill="none" stroke="#8b949e" stroke-width="1.4"/>';
      }
    });
    s.edges.concat(s.stubs).forEach(function (e) {
      if (!e.door) return;
      var a = e.a || e.r, v = DIRS[e.word] || [Math.sign(e.b.x - a.x), Math.sign(e.b.y - a.y)];
      var mx = px(a) + v[0] * U / 2, my = py(a) - v[1] * U / 2;
      g += '<g><title>' + esc(e.door.name) + (e.door.closed ? ' (closed)' : ' (open)') + '</title>' +
        '<rect x="' + (mx - 3.4) + '" y="' + (my - 3.4) + '" width="6.8" height="6.8" transform="rotate(45 ' + mx + ' ' + my + ')" fill="' + (e.door.closed ? '#f0883e' : '#0d1117') + '" stroke="#f0883e" stroke-width="1.3"/></g>';
    });
    s.rooms.forEach(function (o) {
      var r = o.r, x = px(r), y = py(r);
      g += '<g data-id="' + esc(o.id) + '"><title>' + esc(tip(o)) + '</title>' + shapeB(r.terrain, x, y, TERRAIN[r.terrain] || NONE);
      var mark = (o.up ? '▲' : '') + (o.down ? '▼' : '');
      if (mark) g += '<text x="' + (x + 5.5) + '" y="' + (y - 4) + '" font-size="5.5" fill="#e6edf3"' + ((o.up && o.up !== true) || (o.down && o.down !== true) ? ' fill-opacity=".55"' : '') + '>' + mark + '</text>';
      if (o.odd.length) g += '<text x="' + (x - 5.5) + '" y="' + (y - 4) + '" font-size="6" text-anchor="end" fill="' + (o.odd.some(function (q) { return q.kind === 'back'; }) ? BACK : '#e6edf3') + '">↗</text>';
      g += '</g>';
    });
    s.members.forEach(function (m, i) {
      if (!m.here) return;
      var x = px(m.r), y = py(m.r) + 9 + i * 6;
      g += '<text x="' + x + '" y="' + y + '" font-size="5.5" text-anchor="middle" fill="' + GROUP + '" stroke="#0d1117" stroke-width="1.6" paint-order="stroke" font-weight="600">' + esc(m.name) + '</text>';
      g += '<circle cx="' + x + '" cy="' + py(m.r) + '" r="6.6" fill="none" stroke="' + GROUP + '" stroke-width="1.3"/>';
    });
    if (s.you) g += '<circle cx="' + px(s.you) + '" cy="' + py(s.you) + '" r="8.4" fill="' + YOU + '" fill-opacity=".18" stroke="' + YOU + '" stroke-width="2"><title>You</title></circle>';

    var lv = levelText(s), holds = holdsList(view.map), away = awayNote(s);
    return '<div class="B">' +
      '<div class="B-map">' + frame(s, U * 0.95, 30) + defs + g + '</svg>' +
      '<div class="B-tag"><b>' + esc(view.map.area) + '</b>' + (view.map.region ? '<span>' + esc(view.map.region) + '</span>' : '') +
      (lv ? '<span class="B-lv">' + lv + '</span>' : '') + (away ? '<span class="B-away">' + away + '</span>' : '') + '</div></div>' +
      (holds.length ? '<div class="B-side">' + holds.map(function (x) { return '<div class="B-k">' + x.k + '</div>' + x.v.map(function (n) { return '<div>' + esc(n) + '</div>'; }).join(''); }).join('') + '</div>' : '') +
      '</div>';
  }

  // ===============================================================================
  // C — Floor plan: rooms are walled squares that nearly touch, an exit is a gap
  // in the wall, a diagonal is a narrow passage across the corner. Terrain is a
  // flat floor tint plus a glyph; header is a title bar with level steps, holds
  // a single summary line.
  // ===============================================================================

  var GLYPH = { inside: '▫', city: '#', road: '=', field: '"', forest: '♣', water: '≈', swamp: '⸗', cave: '∩', hills: '⌒' };

  function variantC(view, s) {
    var S = 17, h = S / 2, gap = 6, g = '', walls = '', marks = '';
    var open = {}; // room id -> set of sides opened: n e s w
    function openSide(id, w) { (open[id] = open[id] || {})[w] = true; }
    var SIDE = { north: 'n', south: 's', east: 'e', west: 'w' };
    var byRoom = {};
    s.rooms.forEach(function (o) { byRoom[o.r.x + ',' + o.r.y] = o; });
    // passages first, so floors sit over them
    s.edges.forEach(function (e) {
      var ida = idOf(s, e.a), idb = idOf(s, e.b);
      if (!e.diag && !e.far) {
        var v = [e.b.x - e.a.x, e.b.y - e.a.y], sa = v[0] > 0 ? 'e' : v[0] < 0 ? 'w' : v[1] > 0 ? 'n' : 's';
        var sb = { n: 's', s: 'n', e: 'w', w: 'e' }[sa];
        openSide(ida, sa); openSide(idb, sb);
        var x1 = px(e.a), y1 = py(e.a), x2 = px(e.b), y2 = py(e.b);
        g += '<line x1="' + x1 + '" y1="' + y1 + '" x2="' + x2 + '" y2="' + y2 + '" stroke="#30363d" stroke-width="' + gap + '"/>';
      } else {
        g += '<line x1="' + px(e.a) + '" y1="' + py(e.a) + '" x2="' + px(e.b) + '" y2="' + py(e.b) + '" stroke="#30363d" stroke-width="3.2"' + (e.far ? ' stroke-dasharray="3 2"' : '') + '/>' +
          '<line x1="' + px(e.a) + '" y1="' + py(e.a) + '" x2="' + px(e.b) + '" y2="' + py(e.b) + '" stroke="#6e7681" stroke-width=".6" stroke-dasharray="1 1.4"/>';
      }
    });
    s.stubs.forEach(function (st) {
      var x = px(st.r), y = py(st.r), o = off(st.word, U * 0.8), id = idOf(s, st.r);
      if (SIDE[st.word]) openSide(id, SIDE[st.word]);
      var col = st.kind === 'back' ? BACK : '#30363d';
      if (st.kind === 'unexplored') {
        g += '<line x1="' + x + '" y1="' + y + '" x2="' + (x + o[0]) + '" y2="' + (y + o[1]) + '" stroke="#30363d" stroke-width="' + (SIDE[st.word] ? gap : 3.2) + '"/>';
        marks += '<text x="' + (x + o[0]) + '" y="' + (y + o[1] + 2.4) + '" font-size="7" text-anchor="middle" fill="#8b949e">…</text>';
      } else {
        g += '<line x1="' + x + '" y1="' + y + '" x2="' + (x + o[0]) + '" y2="' + (y + o[1]) + '" stroke="' + col + '" stroke-width="' + (SIDE[st.word] ? gap : 3.2) + '"/>';
        var d = off(st.word, 1), ex = x + o[0], ey = y + o[1];
        marks += '<path d="M' + (ex - d[0] * 3 + d[1] * 2.6) + ' ' + (ey - d[1] * 3 - d[0] * 2.6) + 'L' + ex + ' ' + ey + 'L' + (ex - d[0] * 3 - d[1] * 2.6) + ' ' + (ey - d[1] * 3 + d[0] * 2.6) + '" fill="none" stroke="' + (st.kind === 'back' ? BACK : '#8b949e') + '" stroke-width="1.3"/>';
      }
    });
    s.rooms.forEach(function (o) {
      var r = o.r, x = px(r) - h, y = py(r) - h, col = TERRAIN[r.terrain] || NONE, sides = open[o.id] || {};
      g += '<g data-id="' + esc(o.id) + '"><title>' + esc(tip(o)) + '</title>' +
        '<rect x="' + x + '" y="' + y + '" width="' + S + '" height="' + S + '" fill="#0d1117"/>' +
        '<rect x="' + x + '" y="' + y + '" width="' + S + '" height="' + S + '" fill="' + col + '" fill-opacity="' + (r.terrain ? '.55' : '.2') + '"/>' +
        '<text x="' + (x + 2.2) + '" y="' + (y + 6.6) + '" font-size="6" fill="#e6edf3" fill-opacity=".8">' + (GLYPH[r.terrain] || '') + '</text></g>';
      // four walls, each with a doorway gap when that side is open
      var segs = { n: [x, y, x + S, y], s: [x, y + S, x + S, y + S], w: [x, y, x, y + S], e: [x + S, y, x + S, y + S] };
      keys(segs).forEach(function (k) {
        var q = segs[k];
        if (!sides[k]) { walls += '<line x1="' + q[0] + '" y1="' + q[1] + '" x2="' + q[2] + '" y2="' + q[3] + '"/>'; return; }
        var mx = (q[0] + q[2]) / 2, my = (q[1] + q[3]) / 2, hz = q[1] === q[3], a = gap / 2;
        walls += hz ? '<line x1="' + q[0] + '" y1="' + q[1] + '" x2="' + (mx - a) + '" y2="' + my + '"/><line x1="' + (mx + a) + '" y1="' + q[1] + '" x2="' + q[2] + '" y2="' + my + '"/>'
          : '<line x1="' + q[0] + '" y1="' + q[1] + '" x2="' + mx + '" y2="' + (my - a) + '"/><line x1="' + q[0] + '" y1="' + (my + a) + '" x2="' + mx + '" y2="' + q[3] + '"/>';
      });
      if (o.up) marks += '<text x="' + (x + S - 2) + '" y="' + (y + 6.4) + '" font-size="6.5" text-anchor="end" fill="#e6edf3"' + (o.up !== true ? ' fill-opacity=".5"' : '') + '>↑</text>';
      if (o.down) marks += '<text x="' + (x + S - 2) + '" y="' + (y + S - 2) + '" font-size="6.5" text-anchor="end" fill="#e6edf3"' + (o.down !== true ? ' fill-opacity=".5"' : '') + '>↓</text>';
      if (o.odd.length) marks += '<text x="' + (x + 2) + '" y="' + (y + S - 2.2) + '" font-size="6" fill="' + (o.odd.some(function (q) { return q.kind === 'back'; }) ? BACK : '#e6edf3') + '"><title>' + esc(o.odd.map(function (q) { return q.word; }).join(', ')) + '</title>⇱</text>';
    });
    // doors sit in the doorway: closed = a leaf filling the gap, open = the leaf swung aside
    s.edges.concat(s.stubs).forEach(function (e) {
      if (!e.door) return;
      var a = e.a || e.r, v = DIRS[e.word] || [Math.sign(e.b.x - a.x), Math.sign(e.b.y - a.y)];
      var mx = px(a) + v[0] * h, my = py(a) - v[1] * h, hz = v[1] !== 0, L = gap / 2 + .6;
      var tipT = '<title>' + esc(e.door.name) + (e.door.closed ? ' (closed)' : ' (open)') + '</title>';
      if (e.door.closed) marks += '<line x1="' + (hz ? mx - L : mx) + '" y1="' + (hz ? my : my - L) + '" x2="' + (hz ? mx + L : mx) + '" y2="' + (hz ? my : my + L) + '" stroke="#f0883e" stroke-width="2.6">' + tipT + '</line>';
      else marks += '<line x1="' + (hz ? mx - L : mx) + '" y1="' + (hz ? my : my - L) + '" x2="' + (hz ? mx - L : mx + v[0] * L * 1.6) + '" y2="' + (hz ? my - v[1] * L * 1.6 : my - L) + '" stroke="#f0883e" stroke-width="1.4">' + tipT + '</line>';
    });
    s.members.forEach(function (m, i) {
      if (!m.here) return;
      var x = px(m.r) - h + 4 + i * 5, y = py(m.r) + h - 4;
      marks += '<g><title>' + esc(m.name) + '</title><rect x="' + (x - 3) + '" y="' + (y - 3) + '" width="6" height="6" rx="1" fill="' + GROUP + '"/><text x="' + x + '" y="' + (y + 1.8) + '" font-size="4.8" text-anchor="middle" fill="#0d1117" font-weight="700">' + esc(m.name[0]) + '</text></g>';
    });
    if (s.you) marks += '<g><title>You</title><circle cx="' + px(s.you) + '" cy="' + py(s.you) + '" r="4.6" fill="' + YOU + '" stroke="#0d1117" stroke-width="1.4"/><circle cx="' + px(s.you) + '" cy="' + py(s.you) + '" r="1.5" fill="#0d1117"/></g>';

    var lv = levelText(s), holds = holdsList(view.map), away = awayNote(s);
    var steps = s.zs.length > 1 ? '<span class="C-steps">' + s.zs.slice().reverse().map(function (z) {
      return '<i class="' + (z === s.z ? 'on' : '') + (z === s.youLevel ? ' you' : '') + '" title="Level ' + (s.zs.indexOf(z) + 1) + '"></i>';
    }).join('') + '</span>' : '';
    return '<div class="C">' +
      '<div class="C-bar"><span class="C-area">' + esc(view.map.area) + '</span>' + (view.map.region ? '<span class="C-region">, ' + esc(view.map.region) + '</span>' : '') +
      (lv ? '<span class="C-lv">' + steps + lv + '</span>' : '') + '</div>' +
      '<div class="C-body">' + frame(s, U * 0.95, 32) + g + '<g stroke="#c9d1d9" stroke-width="1.1" stroke-linecap="square">' + walls + '</g>' + marks + '</svg></div>' +
      (away ? '<div class="C-foot">' + away + '</div>' : '') +
      (holds.length ? '<div class="C-foot" title="' + esc(holds.map(function (x) { return x.k + ': ' + x.v.join(', '); }).join('\n')) + '">' +
        holds.map(function (x) { return x.k + ' ' + x.v.length; }).join(' · ') + ': ' + esc(holds.map(function (x) { return x.v.join(', '); }).join('; ')) + '</div>' : '') +
      '</div>';
  }

  function idOf(s, r) { for (var i = 0; i < s.rooms.length; i++) if (s.rooms[i].r === r) return s.rooms[i].id; }

  var CSS = [
    '.mapwin{display:flex;flex-direction:column;height:100%;min-height:0}',
    '.mapwin[data-state="unfed"],.mapwin[data-state="severed"]{opacity:.45}',
    '.plane{width:100%;height:100%;display:block;margin:auto}',
    '.reason{margin:auto;padding:1em;text-align:center;color:#8b949e;max-width:22em}',
    '.reason code{color:#c9d1d9}',
    '.unfed{margin:auto;color:#6e7681}',
    // A
    '.A{display:flex;flex-direction:column;height:100%;min-height:0;gap:4px}',
    '.A-head{display:flex;align-items:baseline;gap:.6em;border-bottom:1px solid #30363d;padding:0 2px 3px;white-space:nowrap;overflow:hidden}',
    '.A-area{font-weight:600;color:#e6edf3}.A-region{color:#8b949e;font-size:.92em}.A-level{margin-left:auto;color:#8b949e;font-size:.92em}',
    '.A-body{flex:1;min-height:0;display:flex}',
    '.A-away{font-size:.85em;color:#8b949e;text-align:center}',
    '.A-holds{border-top:1px solid #30363d;padding-top:3px;font-size:.88em;color:#8b949e}.A-holds b{color:#c9d1d9;font-weight:600}',
    // B
    '.B{display:flex;height:100%;min-height:0;gap:6px}',
    '.B-map{position:relative;flex:1;min-width:0;display:flex}',
    '.B-tag{position:absolute;left:0;top:0;display:flex;flex-direction:column;background:rgba(13,17,23,.78);padding:2px 6px 3px;border-radius:4px;font-size:.92em;pointer-events:none}',
    '.B-tag b{color:#e6edf3}.B-tag span{color:#8b949e;font-size:.92em}.B-lv{color:#ffd33d!important}.B-away{color:#ff7b72!important}',
    '.B-side{width:8.5em;flex:none;border-left:1px solid #30363d;padding-left:6px;font-size:.86em;color:#c9d1d9;overflow:auto}',
    '.B-k{color:#8b949e;text-transform:uppercase;letter-spacing:.06em;font-size:.85em;margin-top:4px}',
    // C
    '.C{display:flex;flex-direction:column;height:100%;min-height:0}',
    '.C-bar{display:flex;align-items:center;background:#161b22;border:1px solid #30363d;border-radius:4px;padding:2px 6px;white-space:nowrap;overflow:hidden}',
    '.C-area{color:#e6edf3;font-weight:600}.C-region{color:#8b949e}',
    '.C-lv{margin-left:auto;display:flex;align-items:center;gap:5px;color:#8b949e;font-size:.9em}',
    '.C-steps{display:inline-flex;flex-direction:column;gap:1px}.C-steps i{display:block;width:12px;height:3px;background:#30363d}.C-steps i.on{background:#c9d1d9}.C-steps i.you{outline:1px solid #ffd33d}',
    '.C-body{flex:1;min-height:0;display:flex;padding:4px 0}',
    '.C-foot{font-size:.86em;color:#8b949e;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
  ].join('\n');

  function render(variant, view) {
    var body;
    if (view.hud === 'unfed' || !view.map && !view.reason) body = '<div class="unfed">Map</div>';
    else if (view.reason && view.hud === 'live') body = '<div class="reason">' + reasonText(view) + '</div>';
    else if (view.reason) body = '<div class="unfed">Map</div>';
    else {
      var s = scene(view);
      body = variant === 'B' ? variantB(view, s) : variant === 'C' ? variantC(view, s) : variantA(view, s, variant === 'D');
    }
    return '<div class="mapwin" data-state="' + (view.hud || 'live') + '">' + body + '</div>';
  }

  root.MapLook = { render: render, CSS: CSS, scene: scene, levels: levels, shownLevel: shownLevel,
    NAMES: { A: 'Tiles, texture', D: 'Tiles, one motif', B: 'Nodes and lines', C: 'Floor plan' } };
})(typeof window !== 'undefined' ? window : globalThis);

// PROTOTYPE — throwaway (wayfinder ticket "How the player steps between levels", map #17).
// Four level controls on look A "Tiles" (../map-look/render.js). Each control is
// plain HTML/SVG whose clickable parts carry data-mud-action="level" and
// data-mud-data="<z>" or "mine", so a click goes to Lua exactly as the real window's
// would. Lua owns Browsing; this file only draws.
//
//   LevelCtl.view(variant, view) -> view with levelHtml / awayHtml / sideHtml / stairClick
(function (root) {
  function esc(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
  function act(z) { return ' data-mud-action="level" data-mud-data="' + z + '"'; }
  function n(s, z) { return s.zs.indexOf(z) + 1; }
  function browsing(s) { return s.youLevel != null && s.youLevel !== s.z; }
  // who stands on level z: you (yellow) and members (coral)
  function dots(s, z) {
    var d = '';
    if (s.youLevel === z) d += '<i class="L-dy" title="You"></i>';
    s.members.forEach(function (m) { if (m.r.z === z) d += '<i class="L-dm" title="' + esc(m.name) + '"></i>'; });
    return d;
  }
  // members on another level than the one shown; you too, while Browsing
  function away(s, withBack) {
    var t = [];
    if (browsing(s)) t.push('You: level ' + n(s, s.youLevel) + (withBack ? ' <button class="L-back"' + act('mine') + '>back to you</button>' : ''));
    s.members.forEach(function (m) { if (!m.here) t.push(esc(m.name) + ': level ' + n(s, m.r.z)); });
    return t.join(' · ');
  }

  var V = {
    // A — Stepper: ▼ Level n of m ▲ at the right of the header bar.
    A: function (v) {
      v.levelHtml = function (s) {
        if (s.zs.length < 2) return '';
        var i = s.zs.indexOf(s.z), lo = s.zs[i - 1], hi = s.zs[i + 1];
        return '<span class="L-step">' +
          '<button title="Level below"' + (lo == null ? ' disabled' : act(lo)) + '>▼</button>' +
          '<span class="' + (browsing(s) ? 'L-br' : '') + '">Level ' + (i + 1) + ' of ' + s.zs.length + '</span>' +
          '<button title="Level above"' + (hi == null ? ' disabled' : act(hi)) + '>▲</button></span>';
      };
      v.awayHtml = function (s) { return away(s, true); };
      return v;
    },
    // B — Chips: one numbered chip per level in the header; the shown one filled,
    // yellow/coral dots for who is on each.
    B: function (v) {
      v.levelHtml = function (s) {
        if (s.zs.length < 2) return '';
        return '<span class="L-chips">' + s.zs.map(function (z) {
          return '<button class="' + (z === s.z ? 'on' : '') + '" title="Level ' + n(s, z) + '"' + act(z) + '>' + n(s, z) + dots(s, z) + '</button>';
        }).join('') + '</span>';
      };
      v.awayHtml = function (s) { return away(s, false); };
      return v;
    },
    // C — Ladder: a strip down the plane's right edge, highest level on top.
    // The header keeps its "Level n of m" text.
    C: function (v) {
      v.sideHtml = function (s) {
        if (s.zs.length < 2) return '';
        return '<div class="L-ladder">' + s.zs.slice().reverse().map(function (z) {
          return '<button class="' + (z === s.z ? 'on' : '') + '" title="Level ' + n(s, z) + '"' + act(z) + '>' + n(s, z) + '<span>' + dots(s, z) + '</span></button>';
        }).join('') + '</div>';
      };
      v.awayHtml = function (s) { return away(s, false); };
      return v;
    },
    // D — Stairs: no buttons. Click a white up/down mark on the plane to show the
    // level it leads to; while Browsing the header offers the way back.
    D: function (v) {
      v.stairClick = true;
      v.levelHtml = function (s) {
        if (s.zs.length < 2) return '';
        return '<span class="' + (browsing(s) ? 'L-br' : '') + '">Level ' + n(s, s.z) + ' of ' + s.zs.length + '</span>' +
          (browsing(s) ? ' <button class="L-back"' + act('mine') + '>↩ yours</button>' : '');
      };
      return v;
    },
  };

  // E/F — the header holds only the names; a bar under the plane holds
  // ▼ Level n of m ▲, and who is on other levels sits by the arrow that leads to them
  // (instead of the "Rei: level 2" line). E draws each one as the map's own marker
  // (coral initial, yellow ring for you); F folds members into a count.
  function footer(s, side) {
    if (s.zs.length < 2) return '';
    var i = s.zs.indexOf(s.z), lo = s.zs[i - 1], hi = s.zs[i + 1];
    var who = { up: [], down: [] };
    if (browsing(s)) who[s.youLevel > s.z ? 'up' : 'down'].push({ you: true, z: s.youLevel });
    s.members.forEach(function (m) { if (!m.here) who[m.r.z > s.z ? 'up' : 'down'].push({ name: m.name, z: m.r.z }); });
    return '<div class="L-foot">' +
      '<span class="L-end"><button title="Level below"' + (lo == null ? ' disabled' : act(lo)) + '>▼</button>' + side(s, who.down) + '</span>' +
      '<span class="L-mid' + (browsing(s) ? ' L-br' : '') + '">Level ' + (i + 1) + ' of ' + s.zs.length + '</span>' +
      '<span class="L-end L-r">' + side(s, who.up) + '<button title="Level above"' + (hi == null ? ' disabled' : act(hi)) + '>▲</button></span></div>';
  }
  function discs(s, list) {
    return list.map(function (w) {
      return w.you ? '<i class="L-you" title="You: level ' + n(s, w.z) + ' (back to you)"' + act('mine') + '></i>'
        : '<i class="L-mem" title="' + esc(w.name) + ': level ' + n(s, w.z) + '"' + act(w.z) + '>' + esc(w.name[0]) + '</i>';
    }).join('');
  }
  function counts(s, list) {
    var you = list.filter(function (w) { return w.you; }), mem = list.filter(function (w) { return !w.you; });
    return (you.length ? '<i class="L-you" title="You: level ' + n(s, you[0].z) + ' (back to you)"' + act('mine') + '></i>' : '') +
      (mem.length ? '<span class="L-cnt" title="' + esc(mem.map(function (w) { return w.name + ': level ' + n(s, w.z); }).join('\n')) + '"><i class="L-dm"></i>' + mem.length + '</span>' : '');
  }
  function foot(side) {
    return function (v) {
      v.levelHtml = function () { return ''; };
      v.awayHtml = function () { return ''; };
      v.footHtml = function (s) { return footer(s, side); };
      return v;
    };
  }
  V.E = foot(discs);
  V.F = foot(counts);

  var CSS = [
    '.L-foot{display:flex;align-items:center;border-top:1px solid #30363d;padding-top:3px;font-size:.92em;color:#8b949e}',
    '.L-end{flex:1;display:flex;align-items:center;gap:3px;min-width:0}.L-r{justify-content:flex-end}',
    '.L-mid{flex:none;padding:0 .5em;white-space:nowrap}',
    '.L-foot button{background:#161b22;color:#c9d1d9;border:1px solid #30363d;border-radius:3px;font:inherit;cursor:pointer;line-height:1.2;padding:0 6px}',
    '.L-foot button:disabled{opacity:.3;cursor:default}.L-foot button:not(:disabled):hover{border-color:#8b949e;color:#fff}',
    '.L-mem{display:inline-flex;align-items:center;justify-content:center;width:1.25em;height:1.25em;border-radius:50%;background:#ff7b72;color:#0d1117;font-style:normal;font-weight:700;font-size:.82em;cursor:pointer;flex:none}',
    '.L-you{display:inline-block;width:.95em;height:.95em;border-radius:3px;border:2px solid #ffd33d;cursor:pointer;flex:none;box-sizing:border-box;position:relative}',
    '.L-you::after{content:"";position:absolute;left:50%;top:50%;width:3px;height:3px;margin:-1.5px;border-radius:50%;background:#ffd33d}',
    '.L-cnt{display:inline-flex;align-items:center;gap:2px;color:#ff7b72;font-weight:600}',
    '.L-mem:hover,.L-you:hover{outline:1px solid #fff}',
    '.L-step{display:inline-flex;align-items:center;gap:4px}',
    '.L-step button,.L-chips button,.L-ladder button,.L-back{background:#161b22;color:#c9d1d9;border:1px solid #30363d;border-radius:3px;font:inherit;cursor:pointer;line-height:1.2}',
    '.L-step button{padding:0 5px;font-size:.85em}',
    '.L-step button:disabled{opacity:.3;cursor:default}',
    '.L-step button:not(:disabled):hover,.L-chips button:hover,.L-ladder button:hover,.L-back:hover{border-color:#8b949e;color:#fff}',
    '.L-br{color:#39c5cf}',
    '.L-chips{display:inline-flex;gap:3px;align-items:center}',
    '.L-chips button{position:relative;min-width:1.7em;padding:0 4px}',
    '.L-chips button.on,.L-ladder button.on{background:#c9d1d9;color:#0d1117;border-color:#c9d1d9;font-weight:600}',
    '.L-dy,.L-dm{display:inline-block;width:5px;height:5px;border-radius:50%;margin-left:2px;vertical-align:middle;box-shadow:0 0 0 1px #0d1117}',
    '.L-dy{background:#ffd33d}.L-dm{background:#ff7b72}',
    '.L-ladder{flex:none;display:flex;flex-direction:column;justify-content:center;gap:3px;padding-left:4px;border-left:1px solid #30363d}',
    '.L-ladder button{width:2.3em;padding:2px 0;display:flex;flex-direction:column;align-items:center}',
    '.L-ladder button span{height:6px;line-height:0}',
    '.L-back{font-size:.85em;padding:0 5px;color:#39c5cf;border-color:#1b4e53}',
    '.stair{cursor:pointer}.stair:hover path{fill:#39c5cf}',
  ].join('\n');

  root.LevelCtl = {
    view: function (variant, view) { return (V[variant] || V.A)(view); },
    CSS: CSS, VARIANTS: ['E', 'F', 'A', 'B', 'C', 'D'],
    NAMES: { A: 'Stepper in the header', B: 'Chips in the header', C: 'Ladder at the side', D: 'Click the stairs', E: 'Footer, markers by the arrows', F: 'Footer, counts by the arrows' },
  };
})(typeof window !== 'undefined' ? window : globalThis);

var css=document.createElement('style');css.textContent=MapLook.CSS+'\n'+LevelCtl.CSS;document.head.appendChild(css);
var V='E',map=null,where=null,level=null;
function reason(){ if(!map) return 'nomap'; if(!Object.keys(map.rooms||{}).length) return 'nocells';
  if(where && !where.here) return 'offplane'; return null; }
function draw(){
  var view={hud:'live',map:map,where:where&&map&&map.rooms[where.here]?where:{members:(where||{}).members||{}},level:level,reason:reason()};
  document.getElementById('out').innerHTML=MapLook.render('A',LevelCtl.view(V,view));
  [].forEach.call(document.querySelectorAll('#pick [data-v]'),function(b){b.className=b.dataset.v===V?'on':''});
}
document.getElementById('pick').addEventListener('click',function(e){
  var b=e.target.closest('button');if(!b||!b.dataset.v)return;V=b.dataset.v;mudforge.send('variant',{v:V});draw();
});
mudforge.onMessage(function(d){
  if(d.v) V=d.v;
  if('map' in d) map=d.map;
  if('where' in d) where=d.where;
  level=d.level==null?null:d.level;
  draw();
});
draw();mudforge.send('ready',{});
</script>
]==]

local id, lastMap, lastWhere, variant, level = nil, nil, nil, "E", nil

local function myZ()
  local here = lastWhere and lastWhere.here
  local r = here and lastMap and lastMap.rooms and lastMap.rooms[here]
  return r and r.z
end

local function push()
  if not id then return end
  sendWidgetMessage(id, { v = variant, map = lastMap, where = lastWhere, level = level })
end

function init()
  id = createWidget({
    type = "html", name = "map-levels-prototype", title = "Map levels (prototype)",
    position = { x = 80, y = 80 }, size = { width = 420, height = 440 },
  })
  setWidgetProperty(id, "content", CONTENT)
  registerWidgetEvent(id, "luamsg", function(m)
    if m.event == "variant" and m.data then variant = m.data.v end
    if m.event == "ready" then push() end
  end)
  registerWidgetEvent(id, "action", function(d)
    if d.action ~= "level" then return end
    local z = (d.data ~= "mine") and tonumber(d.data) or nil
    if z == myZ() then z = nil end -- showing your own level is not Browsing
    level = z
    push()
  end)
  onGMCPUpdate("Area.Map", function(pkg)
    if not lastMap or lastMap.area ~= pkg.area then level = nil end -- another Area ends Browsing
    lastMap = pkg; push()
  end)
  onGMCPUpdate("Area.Where", function(pkg)
    if not lastWhere or lastWhere.here ~= pkg.here then level = nil end -- moving ends Browsing
    lastWhere = pkg; push()
  end)
  sendGMCP("Core.Hello", { client = "MudForge", version = "map-levels-prototype" })
end
