// PROTOTYPE build step: node build-lua.js
// Pulls the shared CSS + the six <template id="effects-X|slots-X"> blocks out of
// preview.html, expands their row pools, and writes
// textdungeon-hud-effects-slots-prototype.lua — a MudForge plugin that mounts
// all six variants as real html widgets fed by the live Char.Effects /
// Char.Items feed. Single source of truth for the markup = preview.html.
const fs = require('fs');
const path = require('path');
const html = fs.readFileSync(path.join(__dirname, 'preview.html'), 'utf8');

function expandPool(s) {
  return s.replace(/<!--pool:(\d+)-->([\s\S]*?)<!--\/pool-->/g, (_, n, row) =>
    Array.from({ length: +n }, (_, i) => row.replace(/\{i\}/g, i + 1)).join(''));
}

const shared = /<template id="css-shared">([\s\S]*?)<\/template>/.exec(html)[1].trim();
const variants = [];
const re = /<template id="(effects|slots)-([A-Z])" data-name="([^"]+)" data-size="(\d+)x(\d+)">([\s\S]*?)<\/template>/g;
let m;
while ((m = re.exec(html))) {
  const [, kind, key, name, w, h, body] = m;
  const content = expandPool(shared + '\n' + body.trim());
  if (content.includes(']==]')) throw new Error('markup contains ]==]');
  variants.push({ kind, key, name, w: +w, h: +h, content });
}
if (variants.length !== 6) throw new Error('expected 6 variants, got ' + variants.length);

// effects down the left edge, slots down a second column
const y = { effects: 40, slots: 40 };
const luaVariants = variants.map(v => {
  const x = v.kind === 'effects' ? 20 : 300;
  const s = `  { kind = "${v.kind}", key = "${v.key}", name = "${v.name}", width = ${v.w}, height = ${v.h}, x = ${x}, y = ${y[v.kind]},
    content = [==[
${v.content}
]==] },`;
  y[v.kind] += v.h + 60;
  return s;
}).join('\n');

const lua = `-- PROTOTYPE — throwaway. Generated by prototype/effects-slots/build-lua.js from
-- preview.html; edit the HTML, not this file. Mounts three Effects widget
-- variants (A: Timer rows, B: Chips, C: Ladder) and three Slots widget variants
-- (A: Ledger, B: Paperdoll, C: Held / Worn) so they can be judged against the
-- real Char.Effects / Char.Items feed from a local TextDungeonC.
-- Wayfinder ticket #6, map #1.
--
-- List handling under test: every widget is a FIXED POOL of rows set once as
-- content; membership changes only flip per-row bound values (display), so the
-- content is never rewritten and no binding is ever lost.
plugin = {
  id = "textdungeon-hud-effects-slots-prototype",
  name = "textdungeon-hud-effects-slots-prototype",
  version = "0.0.1",
  author = "wccrawford",
  description = "PROTOTYPE: three Effects + three Slots widget variants for TextDungeon, fed by the GMCP Feed. Throwaway.",
  settings = { saveState = true },
}

local VARIANTS = {
${luaVariants}
}

local EFF_POOL, SLOT_POOL, HELD_POOL = 10, 16, 4

local widgets = { effects = {}, slots = {} }
local anchors = {}      -- { {name=, endsLocal=, span=}, ... } re-anchored on every Char.Effects push, drained by the tick
local tickTimer = nil

local function pushAll(kind, keys)
  for _, id in ipairs(widgets[kind]) do setBoundValues(id, keys) end
end

-- Cadence-agnostic: every push re-anchors remaining = ends_at_ms - now_ms on the local clock.
-- span = the longest remaining ever seen for that name; the draining hairline is left / span.
local function onEffects(pkg)
  local now = getCurrentTime()
  local prev = {}
  for _, a in ipairs(anchors) do prev[a.name] = a end
  anchors = {}
  for _, e in ipairs((pkg and pkg.effects) or {}) do
    if e.name and e.ends_at_ms then
      local left = e.ends_at_ms - (pkg.now_ms or 0)
      local span = left
      if prev[e.name] and prev[e.name].span > span then span = prev[e.name].span end
      anchors[#anchors + 1] = { name = e.name, endsLocal = now + left, span = span }
    end
  end
end

-- string.format has no width specifiers in MudForge's Lua, so pad by hand.
local function mmss(ms)
  if ms < 0 then ms = 0 end
  local s = math.ceil(ms / 1000)
  local m = math.floor(s / 60)
  local r = s - m * 60
  return m .. ":" .. (r < 10 and "0" or "") .. r
end

local function effectsKeys()
  local now = getCurrentTime()
  local live = {}
  for _, a in ipairs(anchors) do
    if a.endsLocal > now then live[#live + 1] = a end
  end
  table.sort(live, function(x, y) return x.endsLocal < y.endsLocal end)
  local k = {
    effEmpty = (#live > 0) and "none" or "",
    effMore = (#live > EFF_POOL) and ("+" .. (#live - EFF_POOL) .. " more") or "",
  }
  for i = 1, EFF_POOL do
    local a = live[i]
    local p = "e" .. i
    if a then
      local left = a.endsLocal - now
      k[p .. "n"] = a.name
      k[p .. "t"] = mmss(left)
      k[p .. "u"] = (left < 5000) and 1 or 0
      k[p .. "p"] = ((a.span > 0) and (left / a.span * 100) or 0) .. "%"
      k[p .. "d"] = ""
      k[p .. "c"] = (i == 1) and "r top" or "r"
    else
      k[p .. "n"] = ""; k[p .. "t"] = ""; k[p .. "u"] = 0; k[p .. "p"] = "0%"; k[p .. "d"] = "none"; k[p .. "c"] = "r"
    end
  end
  return k
end

-- Paperdoll anchoring by slot label; anything else flows in after (grid-area: auto).
local DOLL = {
  ["Neck"] = "1/1", ["Head"] = "1/2", ["Back"] = "1/3",
  ["Hand 1"] = "2/1", ["Body"] = "2/2", ["Hand 2"] = "2/3",
  ["Finger 1"] = "3/1", ["Waist"] = "3/2", ["Finger 2"] = "3/3",
  ["Hands"] = "4/1", ["Legs"] = "4/2", ["Feet"] = "5/2",
}
local function isHeld(label)
  return label == "Hand" or string.match(label, "^Hand %d+$") ~= nil
end

local function slotsKeys(pkg)
  -- Copy through ipairs: in MudForge the raw GMCP array skipped its first element under list[i]
  -- (Head vanished from Ledger/Paperdoll but not from Held / Worn, which was built with ipairs).
  local list = {}
  for _, s in ipairs((pkg and pkg.slots) or {}) do list[#list + 1] = s end
  print("[effects-slots] Char.Items raw #slots=" .. tostring(#((pkg and pkg.slots) or {})) .. " raw[0]=" .. tostring(((pkg and pkg.slots) or {})[0] and ((pkg and pkg.slots) or {})[0].slot) .. " raw[1]=" .. tostring(((pkg and pkg.slots) or {})[1] and ((pkg and pkg.slots) or {})[1].slot) .. " copied=" .. #list)
  local k = { slotsEmpty = (#list > 0) and "none" or "" }
  local function row(prefix, i, s, dash)
    local p = prefix .. i
    if s then
      k[p .. "l"] = s.slot or ""
      k[p .. "i"] = (s.item ~= nil) and s.item or dash
      k[p .. "e"] = (s.item == nil) and 1 or 0
      k[p .. "d"] = ""
    else
      k[p .. "l"] = ""; k[p .. "i"] = ""; k[p .. "e"] = 1; k[p .. "d"] = "none"
    end
  end
  local held, worn = {}, {}
  for _, s in ipairs(list) do
    if isHeld(s.slot or "") then held[#held + 1] = s else worn[#worn + 1] = s end
  end
  for i = 1, SLOT_POOL do
    local s = list[i]
    row("s", i, s, "—")
    k["s" .. i .. "g"] = (s and DOLL[s.slot]) or "auto"
    row("w", i, worn[i], "")
  end
  for i = 1, HELD_POOL do row("h", i, held[i], "empty") end
  return k
end

local function startTick()
  if tickTimer and tickTimer ~= "" then return end
  tickTimer = addTimer(250, function()
    if #anchors > 0 then pushAll("effects", effectsKeys()) end
  end, true)
end

function init()
  widgets = { effects = {}, slots = {} }
  for _, v in ipairs(VARIANTS) do
    local id = createWidget({
      type = "html",
      name = v.kind .. "-" .. v.key,
      title = v.kind .. " " .. v.key .. " - " .. v.name,
      position = { x = v.x, y = v.y },
      size = { width = v.width, height = v.height },
    })
    setWidgetProperty(id, "content", v.content)
    widgets[v.kind][#widgets[v.kind] + 1] = id
  end

  onGMCPUpdate("Char.Effects", function(p) onEffects(p); pushAll("effects", effectsKeys()) end)
  onGMCPUpdate("Char.Items", function(p) pushAll("slots", slotsKeys(p)) end)

  onEffects(getGMCPData("Char.Effects"))
  pushAll("effects", effectsKeys())
  pushAll("slots", slotsKeys(getGMCPData("Char.Items")))
  -- Re-push shortly after mount: the first push above may land before the widget iframes are
  -- ready (Effects showed all pool rows despite display:none until a later feed push).
  addTimer(750, function()
    onEffects(getGMCPData("Char.Effects"))
    pushAll("effects", effectsKeys())
    pushAll("slots", slotsKeys(getGMCPData("Char.Items")))
    print("[effects-slots] re-pushed bound values 750 ms after mount")
  end, false)
  startTick()
  print("[textdungeon-hud-effects-slots-prototype] mounted Effects A/B/C and Slots A/B/C")
end

function onConnect()
  startTick()   -- timers refuse to start while disconnected
end

function onDisconnect()
  tickTimer = nil
end
`;
fs.writeFileSync(path.join(__dirname, 'textdungeon-hud-effects-slots-prototype.lua'), lua);
console.log('wrote textdungeon-hud-effects-slots-prototype.lua (' + variants.map(v => v.kind + '-' + v.key + ' ' + v.w + 'x' + v.h).join(', ') + ')');
