-- PROTOTYPE — throwaway. Generated by prototype/effects-slots/build-lua.js from
-- preview.html; edit the HTML, not this file. Mounts three Effects widget
-- variants (A: Timer rows, B: Chips, C: Ladder) and three Slots widget variants
-- (A: Ledger, B: Paperdoll, C: Held / Worn) so they can be judged against the
-- real Char.Effects / Char.Items feed from a local TextDungeonC.
-- Wayfinder ticket #6, map #1.
--
-- List handling under test: every widget is a FIXED POOL of rows set once as
-- content; membership changes only flip per-row bound values (display), so the
-- content is never rewritten and no binding is ever lost.
plugin = {
  id = "textdungeon-hud-effects-slots-prototype",
  name = "textdungeon-hud-effects-slots-prototype",
  version = "0.0.1",
  author = "wccrawford",
  description = "PROTOTYPE: three Effects + three Slots widget variants for TextDungeon, fed by the GMCP Feed. Throwaway.",
  settings = { saveState = true },
}

local VARIANTS = {
  { kind = "effects", key = "A", name = "Timer rows", width = 240, height = 132, x = 20, y = 40,
    content = [==[
<style>
  html,body{margin:0;padding:0;background:transparent;color:#c9d1d9;font:12px/1.25 "Segoe UI",system-ui,sans-serif;overflow:hidden}
  *{box-sizing:border-box}
  /* urgency: 0 normal, 1 under 5 s */
  [data-urg="0"]{--u:#58a6ff}[data-urg="1"]{--u:#e5232b}
  /* slot occupancy: 1 = empty */
  [data-empty="1"]{--i:#4b5563;--l:#4b5563}[data-empty="0"]{--i:#c9d1d9;--l:#8b949e}
  .empty{color:#6e7681;font-size:11px;font-style:italic}
</style>
<style>
  .list{display:flex;flex-direction:column;gap:4px}
  .e{display:flex;flex-direction:column;gap:2px}
  .e .l{display:flex;justify-content:space-between;align-items:baseline;gap:8px}
  .e .n{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
  .e .t{color:var(--u);font-variant-numeric:tabular-nums;font-size:11px;font-weight:600}
  .e .h{height:3px;background:#30363d;border-radius:2px;overflow:hidden}
  .e .h div{height:100%;background:var(--u);transition:width .25s linear}
</style>
<div class="list">
  <div class="empty" data-mud-bind-style="display:effEmpty">No effects</div>
  
  <div class="e" data-mud-bind-attr="data-urg:e1u" data-mud-bind-style="display:e1d">
    <div class="l"><span class="n" data-mud-bind="e1n"></span><span class="t" data-mud-bind="e1t"></span></div>
    <div class="h"><div data-mud-bind-style="width:e1p"></div></div>
  </div>
  
  <div class="e" data-mud-bind-attr="data-urg:e2u" data-mud-bind-style="display:e2d">
    <div class="l"><span class="n" data-mud-bind="e2n"></span><span class="t" data-mud-bind="e2t"></span></div>
    <div class="h"><div data-mud-bind-style="width:e2p"></div></div>
  </div>
  
  <div class="e" data-mud-bind-attr="data-urg:e3u" data-mud-bind-style="display:e3d">
    <div class="l"><span class="n" data-mud-bind="e3n"></span><span class="t" data-mud-bind="e3t"></span></div>
    <div class="h"><div data-mud-bind-style="width:e3p"></div></div>
  </div>
  
  <div class="e" data-mud-bind-attr="data-urg:e4u" data-mud-bind-style="display:e4d">
    <div class="l"><span class="n" data-mud-bind="e4n"></span><span class="t" data-mud-bind="e4t"></span></div>
    <div class="h"><div data-mud-bind-style="width:e4p"></div></div>
  </div>
  
  <div class="e" data-mud-bind-attr="data-urg:e5u" data-mud-bind-style="display:e5d">
    <div class="l"><span class="n" data-mud-bind="e5n"></span><span class="t" data-mud-bind="e5t"></span></div>
    <div class="h"><div data-mud-bind-style="width:e5p"></div></div>
  </div>
  
  <div class="e" data-mud-bind-attr="data-urg:e6u" data-mud-bind-style="display:e6d">
    <div class="l"><span class="n" data-mud-bind="e6n"></span><span class="t" data-mud-bind="e6t"></span></div>
    <div class="h"><div data-mud-bind-style="width:e6p"></div></div>
  </div>
  
  <div class="e" data-mud-bind-attr="data-urg:e7u" data-mud-bind-style="display:e7d">
    <div class="l"><span class="n" data-mud-bind="e7n"></span><span class="t" data-mud-bind="e7t"></span></div>
    <div class="h"><div data-mud-bind-style="width:e7p"></div></div>
  </div>
  
  <div class="e" data-mud-bind-attr="data-urg:e8u" data-mud-bind-style="display:e8d">
    <div class="l"><span class="n" data-mud-bind="e8n"></span><span class="t" data-mud-bind="e8t"></span></div>
    <div class="h"><div data-mud-bind-style="width:e8p"></div></div>
  </div>
  
  <div class="e" data-mud-bind-attr="data-urg:e9u" data-mud-bind-style="display:e9d">
    <div class="l"><span class="n" data-mud-bind="e9n"></span><span class="t" data-mud-bind="e9t"></span></div>
    <div class="h"><div data-mud-bind-style="width:e9p"></div></div>
  </div>
  
  <div class="e" data-mud-bind-attr="data-urg:e10u" data-mud-bind-style="display:e10d">
    <div class="l"><span class="n" data-mud-bind="e10n"></span><span class="t" data-mud-bind="e10t"></span></div>
    <div class="h"><div data-mud-bind-style="width:e10p"></div></div>
  </div>
  
  <div class="empty" data-mud-bind="effMore"></div>
</div>
]==] },
  { kind = "effects", key = "B", name = "Chips", width = 240, height = 92, x = 20, y = 232,
    content = [==[
<style>
  html,body{margin:0;padding:0;background:transparent;color:#c9d1d9;font:12px/1.25 "Segoe UI",system-ui,sans-serif;overflow:hidden}
  *{box-sizing:border-box}
  /* urgency: 0 normal, 1 under 5 s */
  [data-urg="0"]{--u:#58a6ff}[data-urg="1"]{--u:#e5232b}
  /* slot occupancy: 1 = empty */
  [data-empty="1"]{--i:#4b5563;--l:#4b5563}[data-empty="0"]{--i:#c9d1d9;--l:#8b949e}
  .empty{color:#6e7681;font-size:11px;font-style:italic}
</style>
<style>
  .chips{display:flex;flex-wrap:wrap;gap:4px;align-content:flex-start}
  .c{display:inline-flex;align-items:center;gap:5px;max-width:100%;padding:2px 7px;border:1px solid var(--u);border-radius:999px;background:#0d1117;font-size:11px;line-height:1.2}
  .c .n{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
  .c .t{color:var(--u);font-variant-numeric:tabular-nums;font-weight:600}
</style>
<div class="chips">
  <span class="empty" data-mud-bind-style="display:effEmpty">No effects</span>
  
  <span class="c" data-mud-bind-attr="data-urg:e1u" data-mud-bind-style="display:e1d"><span class="n" data-mud-bind="e1n"></span><span class="t" data-mud-bind="e1t"></span></span>
  
  <span class="c" data-mud-bind-attr="data-urg:e2u" data-mud-bind-style="display:e2d"><span class="n" data-mud-bind="e2n"></span><span class="t" data-mud-bind="e2t"></span></span>
  
  <span class="c" data-mud-bind-attr="data-urg:e3u" data-mud-bind-style="display:e3d"><span class="n" data-mud-bind="e3n"></span><span class="t" data-mud-bind="e3t"></span></span>
  
  <span class="c" data-mud-bind-attr="data-urg:e4u" data-mud-bind-style="display:e4d"><span class="n" data-mud-bind="e4n"></span><span class="t" data-mud-bind="e4t"></span></span>
  
  <span class="c" data-mud-bind-attr="data-urg:e5u" data-mud-bind-style="display:e5d"><span class="n" data-mud-bind="e5n"></span><span class="t" data-mud-bind="e5t"></span></span>
  
  <span class="c" data-mud-bind-attr="data-urg:e6u" data-mud-bind-style="display:e6d"><span class="n" data-mud-bind="e6n"></span><span class="t" data-mud-bind="e6t"></span></span>
  
  <span class="c" data-mud-bind-attr="data-urg:e7u" data-mud-bind-style="display:e7d"><span class="n" data-mud-bind="e7n"></span><span class="t" data-mud-bind="e7t"></span></span>
  
  <span class="c" data-mud-bind-attr="data-urg:e8u" data-mud-bind-style="display:e8d"><span class="n" data-mud-bind="e8n"></span><span class="t" data-mud-bind="e8t"></span></span>
  
  <span class="c" data-mud-bind-attr="data-urg:e9u" data-mud-bind-style="display:e9d"><span class="n" data-mud-bind="e9n"></span><span class="t" data-mud-bind="e9t"></span></span>
  
  <span class="c" data-mud-bind-attr="data-urg:e10u" data-mud-bind-style="display:e10d"><span class="n" data-mud-bind="e10n"></span><span class="t" data-mud-bind="e10t"></span></span>
  
  <span class="empty" data-mud-bind="effMore"></span>
</div>
]==] },
  { kind = "effects", key = "C", name = "Ladder", width = 240, height = 118, x = 20, y = 384,
    content = [==[
<style>
  html,body{margin:0;padding:0;background:transparent;color:#c9d1d9;font:12px/1.25 "Segoe UI",system-ui,sans-serif;overflow:hidden}
  *{box-sizing:border-box}
  /* urgency: 0 normal, 1 under 5 s */
  [data-urg="0"]{--u:#58a6ff}[data-urg="1"]{--u:#e5232b}
  /* slot occupancy: 1 = empty */
  [data-empty="1"]{--i:#4b5563;--l:#4b5563}[data-empty="0"]{--i:#c9d1d9;--l:#8b949e}
  .empty{color:#6e7681;font-size:11px;font-style:italic}
</style>
<style>
  .lad{display:flex;flex-direction:column;gap:2px}
  .r{display:grid;grid-template-columns:44px 1fr;align-items:center;gap:8px;color:#8b949e}
  .r.top{color:#e6edf3}
  .r .t{color:var(--u);font-variant-numeric:tabular-nums;font-weight:700;font-size:13px;text-align:right}
  .r.top .t{font-size:15px}
  .r .n{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
</style>
<div class="lad">
  <div class="empty" data-mud-bind-style="display:effEmpty">No effects</div>
  
  <div class="r" data-mud-bind-attr="data-urg:e1u; class:e1c" data-mud-bind-style="display:e1d"><span class="t" data-mud-bind="e1t"></span><span class="n" data-mud-bind="e1n"></span></div>
  
  <div class="r" data-mud-bind-attr="data-urg:e2u; class:e2c" data-mud-bind-style="display:e2d"><span class="t" data-mud-bind="e2t"></span><span class="n" data-mud-bind="e2n"></span></div>
  
  <div class="r" data-mud-bind-attr="data-urg:e3u; class:e3c" data-mud-bind-style="display:e3d"><span class="t" data-mud-bind="e3t"></span><span class="n" data-mud-bind="e3n"></span></div>
  
  <div class="r" data-mud-bind-attr="data-urg:e4u; class:e4c" data-mud-bind-style="display:e4d"><span class="t" data-mud-bind="e4t"></span><span class="n" data-mud-bind="e4n"></span></div>
  
  <div class="r" data-mud-bind-attr="data-urg:e5u; class:e5c" data-mud-bind-style="display:e5d"><span class="t" data-mud-bind="e5t"></span><span class="n" data-mud-bind="e5n"></span></div>
  
  <div class="r" data-mud-bind-attr="data-urg:e6u; class:e6c" data-mud-bind-style="display:e6d"><span class="t" data-mud-bind="e6t"></span><span class="n" data-mud-bind="e6n"></span></div>
  
  <div class="r" data-mud-bind-attr="data-urg:e7u; class:e7c" data-mud-bind-style="display:e7d"><span class="t" data-mud-bind="e7t"></span><span class="n" data-mud-bind="e7n"></span></div>
  
  <div class="r" data-mud-bind-attr="data-urg:e8u; class:e8c" data-mud-bind-style="display:e8d"><span class="t" data-mud-bind="e8t"></span><span class="n" data-mud-bind="e8n"></span></div>
  
  <div class="r" data-mud-bind-attr="data-urg:e9u; class:e9c" data-mud-bind-style="display:e9d"><span class="t" data-mud-bind="e9t"></span><span class="n" data-mud-bind="e9n"></span></div>
  
  <div class="r" data-mud-bind-attr="data-urg:e10u; class:e10c" data-mud-bind-style="display:e10d"><span class="t" data-mud-bind="e10t"></span><span class="n" data-mud-bind="e10n"></span></div>
  
  <div class="empty" data-mud-bind="effMore"></div>
</div>
]==] },
  { kind = "slots", key = "A", name = "Ledger", width = 240, height = 192, x = 300, y = 40,
    content = [==[
<style>
  html,body{margin:0;padding:0;background:transparent;color:#c9d1d9;font:12px/1.25 "Segoe UI",system-ui,sans-serif;overflow:hidden}
  *{box-sizing:border-box}
  /* urgency: 0 normal, 1 under 5 s */
  [data-urg="0"]{--u:#58a6ff}[data-urg="1"]{--u:#e5232b}
  /* slot occupancy: 1 = empty */
  [data-empty="1"]{--i:#4b5563;--l:#4b5563}[data-empty="0"]{--i:#c9d1d9;--l:#8b949e}
  .empty{color:#6e7681;font-size:11px;font-style:italic}
</style>
<style>
  .led{display:flex;flex-direction:column;gap:1px}
  .s{display:grid;grid-template-columns:58px 1fr;gap:6px;align-items:baseline;line-height:1.2}
  .s .l{color:var(--l);font-size:11px;white-space:nowrap}
  .s .i{color:var(--i);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
</style>
<div class="led">
  <div class="empty" data-mud-bind-style="display:slotsEmpty">No slots</div>
  
  <div class="s" data-mud-bind-attr="data-empty:s1e" data-mud-bind-style="display:s1d"><span class="l" data-mud-bind="s1l"></span><span class="i" data-mud-bind="s1i"></span></div>
  
  <div class="s" data-mud-bind-attr="data-empty:s2e" data-mud-bind-style="display:s2d"><span class="l" data-mud-bind="s2l"></span><span class="i" data-mud-bind="s2i"></span></div>
  
  <div class="s" data-mud-bind-attr="data-empty:s3e" data-mud-bind-style="display:s3d"><span class="l" data-mud-bind="s3l"></span><span class="i" data-mud-bind="s3i"></span></div>
  
  <div class="s" data-mud-bind-attr="data-empty:s4e" data-mud-bind-style="display:s4d"><span class="l" data-mud-bind="s4l"></span><span class="i" data-mud-bind="s4i"></span></div>
  
  <div class="s" data-mud-bind-attr="data-empty:s5e" data-mud-bind-style="display:s5d"><span class="l" data-mud-bind="s5l"></span><span class="i" data-mud-bind="s5i"></span></div>
  
  <div class="s" data-mud-bind-attr="data-empty:s6e" data-mud-bind-style="display:s6d"><span class="l" data-mud-bind="s6l"></span><span class="i" data-mud-bind="s6i"></span></div>
  
  <div class="s" data-mud-bind-attr="data-empty:s7e" data-mud-bind-style="display:s7d"><span class="l" data-mud-bind="s7l"></span><span class="i" data-mud-bind="s7i"></span></div>
  
  <div class="s" data-mud-bind-attr="data-empty:s8e" data-mud-bind-style="display:s8d"><span class="l" data-mud-bind="s8l"></span><span class="i" data-mud-bind="s8i"></span></div>
  
  <div class="s" data-mud-bind-attr="data-empty:s9e" data-mud-bind-style="display:s9d"><span class="l" data-mud-bind="s9l"></span><span class="i" data-mud-bind="s9i"></span></div>
  
  <div class="s" data-mud-bind-attr="data-empty:s10e" data-mud-bind-style="display:s10d"><span class="l" data-mud-bind="s10l"></span><span class="i" data-mud-bind="s10i"></span></div>
  
  <div class="s" data-mud-bind-attr="data-empty:s11e" data-mud-bind-style="display:s11d"><span class="l" data-mud-bind="s11l"></span><span class="i" data-mud-bind="s11i"></span></div>
  
  <div class="s" data-mud-bind-attr="data-empty:s12e" data-mud-bind-style="display:s12d"><span class="l" data-mud-bind="s12l"></span><span class="i" data-mud-bind="s12i"></span></div>
  
  <div class="s" data-mud-bind-attr="data-empty:s13e" data-mud-bind-style="display:s13d"><span class="l" data-mud-bind="s13l"></span><span class="i" data-mud-bind="s13i"></span></div>
  
  <div class="s" data-mud-bind-attr="data-empty:s14e" data-mud-bind-style="display:s14d"><span class="l" data-mud-bind="s14l"></span><span class="i" data-mud-bind="s14i"></span></div>
  
  <div class="s" data-mud-bind-attr="data-empty:s15e" data-mud-bind-style="display:s15d"><span class="l" data-mud-bind="s15l"></span><span class="i" data-mud-bind="s15i"></span></div>
  
  <div class="s" data-mud-bind-attr="data-empty:s16e" data-mud-bind-style="display:s16d"><span class="l" data-mud-bind="s16l"></span><span class="i" data-mud-bind="s16i"></span></div>
  
</div>
]==] },
  { kind = "slots", key = "B", name = "Paperdoll", width = 240, height = 150, x = 300, y = 292,
    content = [==[
<style>
  html,body{margin:0;padding:0;background:transparent;color:#c9d1d9;font:12px/1.25 "Segoe UI",system-ui,sans-serif;overflow:hidden}
  *{box-sizing:border-box}
  /* urgency: 0 normal, 1 under 5 s */
  [data-urg="0"]{--u:#58a6ff}[data-urg="1"]{--u:#e5232b}
  /* slot occupancy: 1 = empty */
  [data-empty="1"]{--i:#4b5563;--l:#4b5563}[data-empty="0"]{--i:#c9d1d9;--l:#8b949e}
  .empty{color:#6e7681;font-size:11px;font-style:italic}
</style>
<style>
  .doll{display:grid;grid-template-columns:repeat(3,1fr);grid-auto-rows:25px;gap:3px}
  .t{display:flex;flex-direction:column;justify-content:center;min-width:0;padding:1px 5px;border:1px solid #30363d;border-radius:4px;background:#0d1117;line-height:1.1}
  .t[data-empty="1"]{border-style:dashed;background:transparent}
  .t .l{color:var(--l);font-size:8px;letter-spacing:.06em;text-transform:uppercase;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
  .t .i{color:var(--i);font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
</style>
<div class="doll">
  
  <div class="t" data-mud-bind-attr="data-empty:s1e" data-mud-bind-style="display:s1d; grid-area:s1g"><span class="l" data-mud-bind="s1l"></span><span class="i" data-mud-bind="s1i"></span></div>
  
  <div class="t" data-mud-bind-attr="data-empty:s2e" data-mud-bind-style="display:s2d; grid-area:s2g"><span class="l" data-mud-bind="s2l"></span><span class="i" data-mud-bind="s2i"></span></div>
  
  <div class="t" data-mud-bind-attr="data-empty:s3e" data-mud-bind-style="display:s3d; grid-area:s3g"><span class="l" data-mud-bind="s3l"></span><span class="i" data-mud-bind="s3i"></span></div>
  
  <div class="t" data-mud-bind-attr="data-empty:s4e" data-mud-bind-style="display:s4d; grid-area:s4g"><span class="l" data-mud-bind="s4l"></span><span class="i" data-mud-bind="s4i"></span></div>
  
  <div class="t" data-mud-bind-attr="data-empty:s5e" data-mud-bind-style="display:s5d; grid-area:s5g"><span class="l" data-mud-bind="s5l"></span><span class="i" data-mud-bind="s5i"></span></div>
  
  <div class="t" data-mud-bind-attr="data-empty:s6e" data-mud-bind-style="display:s6d; grid-area:s6g"><span class="l" data-mud-bind="s6l"></span><span class="i" data-mud-bind="s6i"></span></div>
  
  <div class="t" data-mud-bind-attr="data-empty:s7e" data-mud-bind-style="display:s7d; grid-area:s7g"><span class="l" data-mud-bind="s7l"></span><span class="i" data-mud-bind="s7i"></span></div>
  
  <div class="t" data-mud-bind-attr="data-empty:s8e" data-mud-bind-style="display:s8d; grid-area:s8g"><span class="l" data-mud-bind="s8l"></span><span class="i" data-mud-bind="s8i"></span></div>
  
  <div class="t" data-mud-bind-attr="data-empty:s9e" data-mud-bind-style="display:s9d; grid-area:s9g"><span class="l" data-mud-bind="s9l"></span><span class="i" data-mud-bind="s9i"></span></div>
  
  <div class="t" data-mud-bind-attr="data-empty:s10e" data-mud-bind-style="display:s10d; grid-area:s10g"><span class="l" data-mud-bind="s10l"></span><span class="i" data-mud-bind="s10i"></span></div>
  
  <div class="t" data-mud-bind-attr="data-empty:s11e" data-mud-bind-style="display:s11d; grid-area:s11g"><span class="l" data-mud-bind="s11l"></span><span class="i" data-mud-bind="s11i"></span></div>
  
  <div class="t" data-mud-bind-attr="data-empty:s12e" data-mud-bind-style="display:s12d; grid-area:s12g"><span class="l" data-mud-bind="s12l"></span><span class="i" data-mud-bind="s12i"></span></div>
  
  <div class="t" data-mud-bind-attr="data-empty:s13e" data-mud-bind-style="display:s13d; grid-area:s13g"><span class="l" data-mud-bind="s13l"></span><span class="i" data-mud-bind="s13i"></span></div>
  
  <div class="t" data-mud-bind-attr="data-empty:s14e" data-mud-bind-style="display:s14d; grid-area:s14g"><span class="l" data-mud-bind="s14l"></span><span class="i" data-mud-bind="s14i"></span></div>
  
  <div class="t" data-mud-bind-attr="data-empty:s15e" data-mud-bind-style="display:s15d; grid-area:s15g"><span class="l" data-mud-bind="s15l"></span><span class="i" data-mud-bind="s15i"></span></div>
  
  <div class="t" data-mud-bind-attr="data-empty:s16e" data-mud-bind-style="display:s16d; grid-area:s16g"><span class="l" data-mud-bind="s16l"></span><span class="i" data-mud-bind="s16i"></span></div>
  
</div>
]==] },
  { kind = "slots", key = "C", name = "Held / Worn", width = 240, height = 140, x = 300, y = 502,
    content = [==[
<style>
  html,body{margin:0;padding:0;background:transparent;color:#c9d1d9;font:12px/1.25 "Segoe UI",system-ui,sans-serif;overflow:hidden}
  *{box-sizing:border-box}
  /* urgency: 0 normal, 1 under 5 s */
  [data-urg="0"]{--u:#58a6ff}[data-urg="1"]{--u:#e5232b}
  /* slot occupancy: 1 = empty */
  [data-empty="1"]{--i:#4b5563;--l:#4b5563}[data-empty="0"]{--i:#c9d1d9;--l:#8b949e}
  .empty{color:#6e7681;font-size:11px;font-style:italic}
</style>
<style>
  .hw{display:flex;flex-direction:column;gap:6px}
  .k{font-size:9px;letter-spacing:.08em;text-transform:uppercase;color:#6e7681;margin-bottom:2px}
  .held{display:flex;gap:6px}
  .hb{flex:1 1 0;min-width:0;padding:4px 7px;border:1px solid #30363d;border-radius:4px;background:#0d1117;line-height:1.15}
  .hb[data-empty="1"]{border-style:dashed;background:transparent}
  .hb .l{color:var(--l);font-size:9px;text-transform:uppercase;letter-spacing:.06em;white-space:nowrap}
  .hb .i{color:var(--i);font-size:12px;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
  .worn{font-size:11px;line-height:1.35}
  .w{display:inline-block;max-width:100%;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;vertical-align:bottom}
  .w .l{color:var(--l)}
  .w .i{color:var(--i)}
  .w::after{content:" · ";color:#4b5563}
  .w:last-of-type::after{content:""}
</style>
<div class="hw">
  <div>
    <div class="k">Held</div>
    <div class="held">
      
      <div class="hb" data-mud-bind-attr="data-empty:h1e" data-mud-bind-style="display:h1d"><div class="l" data-mud-bind="h1l"></div><div class="i" data-mud-bind="h1i"></div></div>
      
      <div class="hb" data-mud-bind-attr="data-empty:h2e" data-mud-bind-style="display:h2d"><div class="l" data-mud-bind="h2l"></div><div class="i" data-mud-bind="h2i"></div></div>
      
      <div class="hb" data-mud-bind-attr="data-empty:h3e" data-mud-bind-style="display:h3d"><div class="l" data-mud-bind="h3l"></div><div class="i" data-mud-bind="h3i"></div></div>
      
      <div class="hb" data-mud-bind-attr="data-empty:h4e" data-mud-bind-style="display:h4d"><div class="l" data-mud-bind="h4l"></div><div class="i" data-mud-bind="h4i"></div></div>
      
    </div>
  </div>
  <div>
    <div class="k">Worn</div>
    <div class="worn">
      
      <span class="w" data-mud-bind-attr="data-empty:w1e" data-mud-bind-style="display:w1d"><span class="l" data-mud-bind="w1l"></span> <span class="i" data-mud-bind="w1i"></span></span>
      
      <span class="w" data-mud-bind-attr="data-empty:w2e" data-mud-bind-style="display:w2d"><span class="l" data-mud-bind="w2l"></span> <span class="i" data-mud-bind="w2i"></span></span>
      
      <span class="w" data-mud-bind-attr="data-empty:w3e" data-mud-bind-style="display:w3d"><span class="l" data-mud-bind="w3l"></span> <span class="i" data-mud-bind="w3i"></span></span>
      
      <span class="w" data-mud-bind-attr="data-empty:w4e" data-mud-bind-style="display:w4d"><span class="l" data-mud-bind="w4l"></span> <span class="i" data-mud-bind="w4i"></span></span>
      
      <span class="w" data-mud-bind-attr="data-empty:w5e" data-mud-bind-style="display:w5d"><span class="l" data-mud-bind="w5l"></span> <span class="i" data-mud-bind="w5i"></span></span>
      
      <span class="w" data-mud-bind-attr="data-empty:w6e" data-mud-bind-style="display:w6d"><span class="l" data-mud-bind="w6l"></span> <span class="i" data-mud-bind="w6i"></span></span>
      
      <span class="w" data-mud-bind-attr="data-empty:w7e" data-mud-bind-style="display:w7d"><span class="l" data-mud-bind="w7l"></span> <span class="i" data-mud-bind="w7i"></span></span>
      
      <span class="w" data-mud-bind-attr="data-empty:w8e" data-mud-bind-style="display:w8d"><span class="l" data-mud-bind="w8l"></span> <span class="i" data-mud-bind="w8i"></span></span>
      
      <span class="w" data-mud-bind-attr="data-empty:w9e" data-mud-bind-style="display:w9d"><span class="l" data-mud-bind="w9l"></span> <span class="i" data-mud-bind="w9i"></span></span>
      
      <span class="w" data-mud-bind-attr="data-empty:w10e" data-mud-bind-style="display:w10d"><span class="l" data-mud-bind="w10l"></span> <span class="i" data-mud-bind="w10i"></span></span>
      
      <span class="w" data-mud-bind-attr="data-empty:w11e" data-mud-bind-style="display:w11d"><span class="l" data-mud-bind="w11l"></span> <span class="i" data-mud-bind="w11i"></span></span>
      
      <span class="w" data-mud-bind-attr="data-empty:w12e" data-mud-bind-style="display:w12d"><span class="l" data-mud-bind="w12l"></span> <span class="i" data-mud-bind="w12i"></span></span>
      
      <span class="w" data-mud-bind-attr="data-empty:w13e" data-mud-bind-style="display:w13d"><span class="l" data-mud-bind="w13l"></span> <span class="i" data-mud-bind="w13i"></span></span>
      
      <span class="w" data-mud-bind-attr="data-empty:w14e" data-mud-bind-style="display:w14d"><span class="l" data-mud-bind="w14l"></span> <span class="i" data-mud-bind="w14i"></span></span>
      
      <span class="w" data-mud-bind-attr="data-empty:w15e" data-mud-bind-style="display:w15d"><span class="l" data-mud-bind="w15l"></span> <span class="i" data-mud-bind="w15i"></span></span>
      
      <span class="w" data-mud-bind-attr="data-empty:w16e" data-mud-bind-style="display:w16d"><span class="l" data-mud-bind="w16l"></span> <span class="i" data-mud-bind="w16i"></span></span>
      
    </div>
  </div>
</div>
]==] },
}

local EFF_POOL, SLOT_POOL, HELD_POOL = 10, 16, 4

local widgets = { effects = {}, slots = {} }
local anchors = {}      -- { {name=, endsLocal=, span=}, ... } re-anchored on every Char.Effects push, drained by the tick
local tickTimer = nil

local function pushAll(kind, keys)
  for _, id in ipairs(widgets[kind]) do setBoundValues(id, keys) end
end

-- Cadence-agnostic: every push re-anchors remaining = ends_at_ms - now_ms on the local clock.
-- span = the longest remaining ever seen for that name; the draining hairline is left / span.
local function onEffects(pkg)
  local now = getCurrentTime()
  local prev = {}
  for _, a in ipairs(anchors) do prev[a.name] = a end
  anchors = {}
  for _, e in ipairs((pkg and pkg.effects) or {}) do
    if e.name and e.ends_at_ms then
      local left = e.ends_at_ms - (pkg.now_ms or 0)
      local span = left
      if prev[e.name] and prev[e.name].span > span then span = prev[e.name].span end
      anchors[#anchors + 1] = { name = e.name, endsLocal = now + left, span = span }
    end
  end
end

-- string.format has no width specifiers in MudForge's Lua, so pad by hand.
local function mmss(ms)
  if ms < 0 then ms = 0 end
  local s = math.ceil(ms / 1000)
  local m = math.floor(s / 60)
  local r = s - m * 60
  return m .. ":" .. (r < 10 and "0" or "") .. r
end

local function effectsKeys()
  local now = getCurrentTime()
  local live = {}
  for _, a in ipairs(anchors) do
    if a.endsLocal > now then live[#live + 1] = a end
  end
  table.sort(live, function(x, y) return x.endsLocal < y.endsLocal end)
  local k = {
    effEmpty = (#live > 0) and "none" or "",
    effMore = (#live > EFF_POOL) and ("+" .. (#live - EFF_POOL) .. " more") or "",
  }
  for i = 1, EFF_POOL do
    local a = live[i]
    local p = "e" .. i
    if a then
      local left = a.endsLocal - now
      k[p .. "n"] = a.name
      k[p .. "t"] = mmss(left)
      k[p .. "u"] = (left < 5000) and 1 or 0
      k[p .. "p"] = ((a.span > 0) and (left / a.span * 100) or 0) .. "%"
      k[p .. "d"] = ""
      k[p .. "c"] = (i == 1) and "r top" or "r"
    else
      k[p .. "n"] = ""; k[p .. "t"] = ""; k[p .. "u"] = 0; k[p .. "p"] = "0%"; k[p .. "d"] = "none"; k[p .. "c"] = "r"
    end
  end
  return k
end

-- Paperdoll anchoring by slot label; anything else flows in after (grid-area: auto).
local DOLL = {
  ["Neck"] = "1/1", ["Head"] = "1/2", ["Back"] = "1/3",
  ["Hand 1"] = "2/1", ["Body"] = "2/2", ["Hand 2"] = "2/3",
  ["Finger 1"] = "3/1", ["Waist"] = "3/2", ["Finger 2"] = "3/3",
  ["Hands"] = "4/1", ["Legs"] = "4/2", ["Feet"] = "5/2",
}
local function isHeld(label)
  return label == "Hand" or string.match(label, "^Hand %d+$") ~= nil
end

local function slotsKeys(pkg)
  local list = (pkg and pkg.slots) or {}
  local k = { slotsEmpty = (#list > 0) and "none" or "" }
  local function row(prefix, i, s, dash)
    local p = prefix .. i
    if s then
      k[p .. "l"] = s.slot or ""
      k[p .. "i"] = (s.item ~= nil) and s.item or dash
      k[p .. "e"] = (s.item == nil) and 1 or 0
      k[p .. "d"] = ""
    else
      k[p .. "l"] = ""; k[p .. "i"] = ""; k[p .. "e"] = 1; k[p .. "d"] = "none"
    end
  end
  local held, worn = {}, {}
  for _, s in ipairs(list) do
    if isHeld(s.slot or "") then held[#held + 1] = s else worn[#worn + 1] = s end
  end
  for i = 1, SLOT_POOL do
    local s = list[i]
    row("s", i, s, "—")
    k["s" .. i .. "g"] = (s and DOLL[s.slot]) or "auto"
    row("w", i, worn[i], "")
  end
  for i = 1, HELD_POOL do row("h", i, held[i], "empty") end
  return k
end

local function startTick()
  if tickTimer and tickTimer ~= "" then return end
  tickTimer = addTimer(250, function()
    if #anchors > 0 then pushAll("effects", effectsKeys()) end
  end, true)
end

function init()
  widgets = { effects = {}, slots = {} }
  for _, v in ipairs(VARIANTS) do
    local id = createWidget({
      type = "html",
      name = v.kind .. "-" .. v.key,
      title = v.kind .. " " .. v.key .. " - " .. v.name,
      position = { x = v.x, y = v.y },
      size = { width = v.width, height = v.height },
    })
    setWidgetProperty(id, "content", v.content)
    widgets[v.kind][#widgets[v.kind] + 1] = id
  end

  onGMCPUpdate("Char.Effects", function(p) onEffects(p); pushAll("effects", effectsKeys()) end)
  onGMCPUpdate("Char.Items", function(p) pushAll("slots", slotsKeys(p)) end)

  onEffects(getGMCPData("Char.Effects"))
  pushAll("effects", effectsKeys())
  pushAll("slots", slotsKeys(getGMCPData("Char.Items")))
  startTick()
  print("[textdungeon-hud-effects-slots-prototype] mounted Effects A/B/C and Slots A/B/C")
end

function onConnect()
  startTick()   -- timers refuse to start while disconnected
end

function onDisconnect()
  tickTimer = nil
end
