// PROTOTYPE build step: node prototype/map-look/build-lua.js
// Inlines render.js into map-look-prototype.lua, a MudForge plugin with one html
// widget that draws the live Area.Map / Area.Where in any of the three looks.
// The widget's own script draws (fine for a throwaway; the real window draws in Lua).
const fs = require('fs');
const path = require('path');
const dir = __dirname;
const render = fs.readFileSync(path.join(dir, 'render.js'), 'utf8');

const content = `<style>
html,body{margin:0;height:100%;background:transparent;color:#c9d1d9;font:13px/1.25 "Segoe UI",system-ui,sans-serif;overflow:hidden}
*{box-sizing:border-box}
#root{display:flex;flex-direction:column;height:100%;padding:4px}
#out{flex:1;min-height:0}
#pick{display:flex;gap:4px;align-items:center;font-size:11px;color:#8b949e;padding-top:3px;border-top:1px dashed #30363d;margin-top:3px}
#pick button{background:#161b22;color:#c9d1d9;border:1px solid #30363d;border-radius:3px;font:inherit;padding:0 6px;cursor:pointer}
#pick button.on{background:#ffd33d;color:#000}
</style>
<div id="root"><div id="out"></div>
<div id="pick">PROTOTYPE <button data-v="A">A Texture</button><button data-v="D">D Motif</button><button data-v="B">B Nodes</button><button data-v="C">C Plan</button>
<span style="margin-left:auto"></span><button id="dn">▼</button><button id="up">▲</button></div></div>
<script>
${render}
var css=document.createElement('style');css.textContent=MapLook.CSS;document.head.appendChild(css);
var V='A',map=null,where=null,level=null,lastHere=null,lastArea=null;
function reason(){ if(!map) return 'nomap'; if(!Object.keys(map.rooms||{}).length) return 'nocells';
  if(where && !where.here) return 'offplane'; return null; }
function draw(){
  var view={hud:'live',map:map,where:where&&map&&map.rooms[where.here]?where:{members:(where||{}).members||{}},level:level,reason:reason()};
  document.getElementById('out').innerHTML=MapLook.render(V,view);
  [].forEach.call(document.querySelectorAll('#pick [data-v]'),function(b){b.className=b.dataset.v===V?'on':''});
}
document.getElementById('pick').addEventListener('click',function(e){
  var b=e.target.closest('button');if(!b)return;
  if(b.dataset.v){V=b.dataset.v;mudforge.send('variant',{v:V})}
  else if(map&&Object.keys(map.rooms).length){var zs=MapLook.levels(map),cur=MapLook.shownLevel({map:map,where:where||{},level:level}),
    i=zs.indexOf(cur)+(b.id==='up'?1:-1);if(i>=0&&i<zs.length){var mine=where&&map.rooms[where.here]&&map.rooms[where.here].z;level=zs[i]===mine?null:zs[i]}}
  draw();
});
mudforge.onMessage(function(d){
  if(d.v) V=d.v;
  if(d.map){ if(lastArea!==d.map.area) level=null; lastArea=d.map.area; map=d.map; }
  if(d.where){ if(d.where.here!==lastHere) level=null; lastHere=d.where.here; where=d.where; }
  draw();
});
draw();mudforge.send('ready',{});
</script>`;
if (content.includes(']==]')) throw new Error('markup contains ]==]');

const lua = `-- PROTOTYPE — throwaway. Generated by prototype/map-look/build-lua.js from
-- render.js; edit that, not this file. One html widget, "Map (prototype)",
-- drawing the live Area.Map / Area.Where in look A, B or C (buttons in the
-- widget). Wayfinder ticket "What the Map looks like", map #17. Nothing ships.
plugin = {
  id = "map-look-prototype",
  name = "map-look-prototype",
  version = "0.0.1",
  author = "wccrawford",
  description = "PROTOTYPE: three looks for the TextDungeon Map window. Throwaway.",
}

local CONTENT = [==[
${content}
]==]

local id, lastMap, lastWhere, variant = nil, nil, nil, "A"

local function push()
  if not id then return end
  sendWidgetMessage(id, { v = variant, map = lastMap, where = lastWhere })
end

function init()
  id = createWidget({
    type = "html", name = "map-look-prototype", title = "Map (prototype)",
    position = { x = 60, y = 60 }, size = { width = 420, height = 420 },
  })
  setWidgetProperty(id, "content", CONTENT)
  registerWidgetEvent(id, "luamsg", function(m)
    if m.event == "variant" and m.data then variant = m.data.v end
    if m.event == "ready" then push() end
  end)
  onGMCPUpdate("Area.Map", function(pkg) lastMap = pkg; push() end)
  onGMCPUpdate("Area.Where", function(pkg) lastWhere = pkg; push() end)
  -- ask for everything again so the widget isn't empty on import
  sendGMCP("Core.Hello", { client = "MudForge", version = "map-look-prototype" })
end
`;
fs.writeFileSync(path.join(dir, 'map-look-prototype.lua'), lua);
console.log('wrote map-look-prototype.lua', lua.length, 'bytes');
