-- PROTOTYPE build step: luajit prototype/map-look/fixtures-to-js.lua > prototype/map-look/fixtures.js
-- Dumps the captured Area.Map planes (and the Area.Where / Room.Info in the seq files) as JS.
local function enc(v)
  local t = type(v)
  if t == "string" then return string.format("%q", v):gsub("\\n", "\n") end
  if t == "number" or t == "boolean" then return tostring(v) end
  if #v > 0 or next(v) == nil then
    if next(v) == nil then return "{}" end
    local o = {} for i = 1, #v do o[i] = enc(v[i]) end return "[" .. table.concat(o, ",") .. "]"
  end
  local keys = {} for k in pairs(v) do keys[#keys+1] = k end table.sort(keys, function(a,b) return tostring(a)<tostring(b) end)
  local o = {} for _, k in ipairs(keys) do o[#o+1] = string.format("%q", tostring(k)) .. ":" .. enc(v[k]) end
  return "{" .. table.concat(o, ",") .. "}"
end
local names = {"bottleshallows","canopyloft","gildhythe","lees_depth1","lees_depth2","mereroad","spitcut_door_closed","spitcut_entered","spitcut_grown","stoppervaults","stubbing"}
io.write("// GENERATED by fixtures-to-js.lua from tests/fixtures/map. PROTOTYPE.\nconst PLANES = {\n")
for _, n in ipairs(names) do
  local f = io.open("tests/fixtures/map/plane_" .. n .. ".lua"):read("*a")
  local note = f:match("%-%- Area%.Map%. ([^\n]*)")
  io.write(string.format("  %q: { note: %s, map: %s },\n", n, enc(note), enc(dofile("tests/fixtures/map/plane_" .. n .. ".lua"))))
end
io.write("};\n")
-- every Area.Where seen in the seq files, so real 'here's and members are available
io.write("const WHERES = [\n")
for _, s in ipairs({"seq_group","seq_level_change","seq_enter_area","seq_expedition_cross","seq_delve_grow","seq_depth_descend","seq_door_opened","seq_login","seq_step"}) do
  for _, p in ipairs(dofile("tests/fixtures/map/" .. s .. ".lua")) do
    if p.pkg == "Area.Where" then io.write("  { seq: " .. enc(s) .. ", where: " .. enc(p.data) .. " },\n") end
  end
end
io.write("];\n")
