// PROTOTYPE build step: node build-lua.js
// Pulls the shared CSS + the three <template id="variant-X"> blocks out of
// preview.html and writes textdungeon-hud-prototype.lua, a MudForge plugin that
// mounts all three variants as real html widgets fed by the live feed.
// Single source of truth for the markup = preview.html.
const fs = require('fs');
const path = require('path');
const html = fs.readFileSync(path.join(__dirname, 'preview.html'), 'utf8');

const shared = /<template id="css-shared">([\s\S]*?)<\/template>/.exec(html)[1].trim();
const variants = [];
const re = /<template id="variant-([A-Z])" data-name="([^"]+)" data-size="(\d+)x(\d+)">([\s\S]*?)<\/template>/g;
let m;
while ((m = re.exec(html))) {
  const [, key, name, w, h, body] = m;
  const content = shared + '\n' + body.trim();
  if (content.includes(']==]')) throw new Error('markup contains ]==]');
  variants.push({ key, name, w: +w, h: +h, content });
}
if (variants.length !== 3) throw new Error('expected 3 variants, got ' + variants.length);

// stack the three widgets down the left edge with a little air between them
let y = 40;
const luaVariants = variants.map(v => {
  const s = `  { key = "${v.key}", name = "${v.name}", width = ${v.w}, height = ${v.h}, x = 20, y = ${y},
    content = [==[
${v.content}
]==] },`;
  y += v.h + 60;
  return s;
}).join('\n');

const lua = `-- PROTOTYPE — throwaway. Generated by prototype/status-widget/build-lua.js from
-- preview.html; edit the HTML, not this file. Mounts three Status widget
-- variants (A: Stacked meters, B: Prompt strip, C: Word-led) side by side so
-- they can be judged against the real Char.Vitals / Char.RoundTime feed from a
-- local TextDungeonC. Wayfinder ticket #5, map #1.
plugin = {
  id = "textdungeon-hud-prototype",
  name = "textdungeon-hud-prototype",
  version = "0.0.1",
  author = "wccrawford",
  description = "PROTOTYPE: three Status widget variants for TextDungeon, fed by the GMCP Feed. Throwaway.",
  settings = { saveState = true },
}

local VARIANTS = {
${luaVariants}
}

-- Values the widget shows verbatim: bound straight from the package, no code in between.
local DIRECT = {
  condName = "condition.name", condCur = "condition.cur", condMax = "condition.max",
  footName = "footing.name",   footCur = "footing.cur",   footMax = "footing.max",
  focusName = "focus.name",    focusCur = "focus.cur",    focusMax = "focus.max",
  standName = "standing.name", encum = "encumbrance",
}

local widgets = {}
local rtAnchor = nil   -- { total = ms, endsAt = local ms } while a Round Time is running
local tickTimer = nil

local function pushAll(keys)
  for _, id in ipairs(widgets) do setBoundValues(id, keys) end
end

-- Computed keys: fill percentages, tier colours, and held power (whose key is absent when none is held).
local function pct(cur, max)
  if not max or max <= 0 or not cur then return "0%" end
  local p = cur / max * 100
  if p < 0 then p = 0 elseif p > 100 then p = 100 end
  return p .. "%"
end

local function vitalsKeys(v)
  local k = {}
  local meters = { cond = v.condition, foot = v.footing, focus = v.focus }
  for key, m in pairs(meters) do
    if m then
      k[key .. "Tier"] = m.tier
      k[key .. "Pct"] = pct(m.cur, m.max)
      k[key .. "Tip"] = tostring(m.cur) .. "/" .. tostring(m.max)
    end
  end
  if v.power then
    k.powerName = v.power.name; k.powerCur = v.power.cur; k.powerTier = v.power.tier; k.powerDisplay = ""
  else
    k.powerName = ""; k.powerCur = ""; k.powerTier = ""; k.powerDisplay = "none"
  end
  return k
end

local function rtKeys()
  if not rtAnchor then
    return { rtDisplay = "none", rtVisibility = "hidden", rtPct = "0%", rtSec = "" }
  end
  local left = rtAnchor.endsAt - getCurrentTime()
  if left <= 0 then
    rtAnchor = nil
    return rtKeys()
  end
  local tenths = math.floor(left / 100)
  local sec = math.floor(tenths / 10)
  local dec = tenths % 10
  return {
    rtDisplay = "", rtVisibility = "visible",
    rtPct = (left / rtAnchor.total * 100) .. "%",
    rtSec = sec .. "." .. dec .. "s",
  }
end

-- Cadence-agnostic: every push re-anchors remaining = clears_at_ms - now_ms; the timer drains it locally.
local function onRoundTime(p)
  if not p or not p.clears_at_ms or p.clears_at_ms == 0 then rtAnchor = nil; return end
  local left = p.clears_at_ms - (p.now_ms or 0)
  if left <= 0 then rtAnchor = nil; return end
  local now = getCurrentTime()
  local total = left
  if rtAnchor and rtAnchor.endsAt > now and rtAnchor.total > left then total = rtAnchor.total end
  rtAnchor = { total = total, endsAt = now + left }
end

local function startTick()
  if tickTimer and tickTimer ~= "" then return end
  tickTimer = addTimer(100, function()
    if rtAnchor then pushAll(rtKeys()) end
  end, true)
end

function init()
  widgets = {}
  for _, v in ipairs(VARIANTS) do
    local id = createWidget({
      type = "html",
      name = "status-" .. v.key,
      title = "Status " .. v.key .. " - " .. v.name,
      position = { x = v.x, y = v.y },
      size = { width = v.width, height = v.height },
    })
    setWidgetProperty(id, "content", v.content)
    for key, path in pairs(DIRECT) do bindWidgetGMCP(id, key, "Char.Vitals", path) end
    widgets[#widgets + 1] = id
  end

  onGMCPUpdate("Char.Vitals", function(v) pushAll(vitalsKeys(v)) end)
  onGMCPUpdate("Char.RoundTime", function(p) onRoundTime(p); pushAll(rtKeys()) end)

  local v = getGMCPData("Char.Vitals")
  if v then pushAll(vitalsKeys(v)) else pushAll(vitalsKeys({})) end
  onRoundTime(getGMCPData("Char.RoundTime"))
  pushAll(rtKeys())
  startTick()
  print("[textdungeon-hud-prototype] mounted Status variants A, B, C")
end

function onConnect()
  startTick()   -- timers refuse to start while disconnected
end

function onDisconnect()
  tickTimer = nil
  rtAnchor = nil
  pushAll(rtKeys())
end
`;
fs.writeFileSync(path.join(__dirname, 'textdungeon-hud-prototype.lua'), lua);
console.log('wrote textdungeon-hud-prototype.lua (' + variants.map(v => v.key + ' ' + v.w + 'x' + v.h).join(', ') + ')');
