-- PROTOTYPE — throwaway. Generated by prototype/status-widget/build-lua.js from
-- preview.html; edit the HTML, not this file. Mounts three Status widget
-- variants (A: Stacked meters, B: Prompt strip, C: Word-led) side by side so
-- they can be judged against the real Char.Vitals / Char.RoundTime feed from a
-- local TextDungeonC. Wayfinder ticket #5, map #1.
plugin = {
  id = "textdungeon-hud-prototype",
  name = "textdungeon-hud-prototype",
  version = "0.0.1",
  author = "wccrawford",
  description = "PROTOTYPE: three Status widget variants for TextDungeon, fed by the GMCP Feed. Throwaway.",
  settings = { saveState = true },
}

local VARIANTS = {
  { key = "A", name = "Stacked meters", width = 240, height = 132, x = 20, y = 40,
    content = [==[
<style>
  html,body{margin:0;padding:0;background:transparent;color:#c9d1d9;font:12px/1.25 "Segoe UI",system-ui,sans-serif;overflow:hidden}
  *{box-sizing:border-box}
  /* tier ramp: 1 best … 5 worst (Condition/Footing/Focus); power 1 strongest … 4 slightest */
  [data-tier="1"]{--c:#3fb950}[data-tier="2"]{--c:#9bc53d}[data-tier="3"]{--c:#e3b341}[data-tier="4"]{--c:#f0883e}[data-tier="5"]{--c:#f85149}
  [data-ptier="1"]{--p:#c084fc}[data-ptier="2"]{--p:#a78bfa}[data-ptier="3"]{--p:#8b7cf6}[data-ptier="4"]{--p:#6e6ad6}
  .rtc{--rt:#58a6ff}
</style>
<style>
  .hud{display:flex;flex-direction:column;gap:5px;padding:2px 0}
  .row{display:grid;grid-template-columns:62px 1fr 48px;align-items:center;gap:6px}
  .lbl{color:#8b949e;font-size:11px}
  .bar{position:relative;height:16px;background:#0d1117;border:1px solid #30363d;border-radius:3px;overflow:hidden}
  .fill{position:absolute;top:0;bottom:0;left:0;background:var(--c,#555);transition:width .25s}
  .word{position:absolute;inset:0;display:flex;align-items:center;padding-left:6px;font-size:11px;color:#fff;text-shadow:0 0 3px #000,0 0 2px #000}
  .num{color:#8b949e;font-size:11px;text-align:right;font-variant-numeric:tabular-nums}
  .rt{position:relative;height:14px;background:#0d1117;border:1px solid #30363d;border-radius:3px;overflow:hidden;margin-top:2px}
  .rtfill{position:absolute;top:0;bottom:0;left:0;background:var(--rt);transition:width .1s linear}
  .rtsec{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;font-size:11px;color:#fff;text-shadow:0 0 3px #000}
  .foot{display:flex;flex-direction:column;gap:1px;font-size:11px;color:#8b949e;margin-top:2px;white-space:nowrap}
  .foot .l{display:flex;justify-content:space-between}
  .pw{color:var(--p)}
</style>
<div class="hud">
  <div class="row"><span class="lbl">Condition</span>
    <div class="bar"><div class="fill" data-mud-bind-attr="data-tier:condTier" data-mud-bind-style="width:condPct"></div><span class="word" data-mud-bind="condName">?</span></div>
    <span class="num"><span data-mud-bind="condCur">?</span>/<span data-mud-bind="condMax">?</span></span></div>
  <div class="row"><span class="lbl">Footing</span>
    <div class="bar"><div class="fill" data-mud-bind-attr="data-tier:footTier" data-mud-bind-style="width:footPct"></div><span class="word" data-mud-bind="footName">?</span></div>
    <span class="num"><span data-mud-bind="footCur">?</span>/<span data-mud-bind="footMax">?</span></span></div>
  <div class="row"><span class="lbl">Focus</span>
    <div class="bar"><div class="fill" data-mud-bind-attr="data-tier:focusTier" data-mud-bind-style="width:focusPct"></div><span class="word" data-mud-bind="focusName">?</span></div>
    <span class="num"><span data-mud-bind="focusCur">?</span>/<span data-mud-bind="focusMax">?</span></span></div>
  <div class="rt rtc" data-mud-bind-style="display:rtDisplay"><div class="rtfill" data-mud-bind-style="width:rtPct"></div><span class="rtsec" data-mud-bind="rtSec"></span></div>
  <div class="foot">
    <div class="l"><span data-mud-bind="standName">?</span><span>Enc <span data-mud-bind="encum">?</span>%</span></div>
    <div class="pw" data-mud-bind-attr="data-ptier:powerTier" data-mud-bind-style="display:powerDisplay">Holding <span data-mud-bind="powerName"></span> (<span data-mud-bind="powerCur"></span>)</div>
  </div>
</div>
]==] },
  { key = "B", name = "Prompt strip", width = 540, height = 62, x = 20, y = 232,
    content = [==[
<style>
  html,body{margin:0;padding:0;background:transparent;color:#c9d1d9;font:12px/1.25 "Segoe UI",system-ui,sans-serif;overflow:hidden}
  *{box-sizing:border-box}
  /* tier ramp: 1 best … 5 worst (Condition/Footing/Focus); power 1 strongest … 4 slightest */
  [data-tier="1"]{--c:#3fb950}[data-tier="2"]{--c:#9bc53d}[data-tier="3"]{--c:#e3b341}[data-tier="4"]{--c:#f0883e}[data-tier="5"]{--c:#f85149}
  [data-ptier="1"]{--p:#c084fc}[data-ptier="2"]{--p:#a78bfa}[data-ptier="3"]{--p:#8b7cf6}[data-ptier="4"]{--p:#6e6ad6}
  .rtc{--rt:#58a6ff}
</style>
<style>
  .strip{display:flex;flex-direction:column;gap:3px}
  .top{display:flex;align-items:stretch;gap:6px;height:24px}
  .pill{position:relative;flex:1 1 0;border:1px solid #30363d;border-radius:12px;background:#0d1117;overflow:hidden}
  .pfill{position:absolute;top:0;bottom:0;left:0;background:var(--c,#555);opacity:.85;transition:width .25s}
  .ptxt{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;padding:0 8px;color:#fff;text-shadow:0 0 3px #000,0 0 2px #000;font-size:11px;white-space:nowrap}
  .side{display:flex;flex-direction:column;justify-content:center;font-size:10px;color:#8b949e;line-height:1.15;white-space:nowrap;text-align:right}
  .side b{color:#c9d1d9;font-weight:500}
  .pw{color:var(--p)}
  .rtline{position:relative;height:10px;background:#0d1117;border:1px solid #30363d;border-radius:5px;overflow:hidden}
  .rtfill{position:absolute;top:0;bottom:0;left:0;background:var(--rt);transition:width .1s linear}
  .rtsec{position:absolute;right:6px;top:-1px;font-size:9px;color:#fff;text-shadow:0 0 3px #000}
</style>
<div class="strip">
  <div class="top">
    <div class="pill"><div class="pfill" data-mud-bind-attr="data-tier:condTier" data-mud-bind-style="width:condPct"></div>
      <div class="ptxt" data-mud-bind-attr="title:condTip"><span data-mud-bind="condName">?</span></div></div>
    <div class="pill"><div class="pfill" data-mud-bind-attr="data-tier:footTier" data-mud-bind-style="width:footPct"></div>
      <div class="ptxt" data-mud-bind-attr="title:footTip"><span data-mud-bind="footName">?</span></div></div>
    <div class="pill"><div class="pfill" data-mud-bind-attr="data-tier:focusTier" data-mud-bind-style="width:focusPct"></div>
      <div class="ptxt" data-mud-bind-attr="title:focusTip"><span data-mud-bind="focusName">?</span></div></div>
    <div class="side">
      <span class="pw" data-mud-bind-attr="data-ptier:powerTier" data-mud-bind-style="display:powerDisplay"><span data-mud-bind="powerName"></span> (<span data-mud-bind="powerCur"></span>)</span>
      <span><b data-mud-bind="standName">?</b> · Enc <b data-mud-bind="encum">?</b>%</span>
    </div>
  </div>
  <div class="rtline rtc" data-mud-bind-style="display:rtDisplay"><div class="rtfill" data-mud-bind-style="width:rtPct"></div><span class="rtsec" data-mud-bind="rtSec"></span></div>
</div>
]==] },
  { key = "C", name = "Word-led", width = 200, height = 172, x = 20, y = 354,
    content = [==[
<style>
  html,body{margin:0;padding:0;background:transparent;color:#c9d1d9;font:12px/1.25 "Segoe UI",system-ui,sans-serif;overflow:hidden}
  *{box-sizing:border-box}
  /* tier ramp: 1 best … 5 worst (Condition/Footing/Focus); power 1 strongest … 4 slightest */
  [data-tier="1"]{--c:#3fb950}[data-tier="2"]{--c:#9bc53d}[data-tier="3"]{--c:#e3b341}[data-tier="4"]{--c:#f0883e}[data-tier="5"]{--c:#f85149}
  [data-ptier="1"]{--p:#c084fc}[data-ptier="2"]{--p:#a78bfa}[data-ptier="3"]{--p:#8b7cf6}[data-ptier="4"]{--p:#6e6ad6}
  .rtc{--rt:#58a6ff}
</style>
<style>
  .wl{display:grid;grid-template-columns:1fr 54px;gap:0 8px;height:100%}
  .stats{display:flex;flex-direction:column;gap:6px}
  .st{display:flex;flex-direction:column;gap:2px}
  .st .k{display:flex;justify-content:space-between;font-size:9px;letter-spacing:.08em;text-transform:uppercase;color:#6e7681}
  .st .k small{letter-spacing:0;text-transform:none;font-variant-numeric:tabular-nums}
  .st .v{font-size:14px;font-weight:600;color:var(--c,#c9d1d9);line-height:1.1;white-space:nowrap}
  .hair{height:3px;background:#30363d;border-radius:2px;overflow:hidden}
  .hair div{height:100%;background:var(--c,#555);transition:width .25s}
  .misc{font-size:10px;color:#8b949e;margin-top:2px;line-height:1.3;white-space:nowrap}
  .misc .pw{color:var(--p)}
  .rtbox{display:flex;flex-direction:column;align-items:center;justify-content:flex-end;gap:3px;border-left:1px solid #30363d;padding-left:8px}
  .rtnum{font-size:22px;font-weight:700;color:var(--rt);font-variant-numeric:tabular-nums;line-height:1}
  .rtcol{width:10px;flex:1;background:#0d1117;border:1px solid #30363d;border-radius:5px;overflow:hidden;display:flex;flex-direction:column;justify-content:flex-end}
  .rtcol div{width:100%;background:var(--rt);transition:height .1s linear}
  .rtk{font-size:9px;letter-spacing:.08em;text-transform:uppercase;color:#6e7681}
</style>
<div class="wl">
  <div class="stats">
    <div class="st" data-mud-bind-attr="data-tier:condTier"><span class="k">Condition<small><span data-mud-bind="condCur">?</span>/<span data-mud-bind="condMax">?</span></small></span>
      <div class="v" data-mud-bind="condName">?</div>
      <div class="hair"><div data-mud-bind-style="width:condPct"></div></div></div>
    <div class="st" data-mud-bind-attr="data-tier:footTier"><span class="k">Footing<small><span data-mud-bind="footCur">?</span>/<span data-mud-bind="footMax">?</span></small></span>
      <div class="v" data-mud-bind="footName">?</div>
      <div class="hair"><div data-mud-bind-style="width:footPct"></div></div></div>
    <div class="st" data-mud-bind-attr="data-tier:focusTier"><span class="k">Focus<small><span data-mud-bind="focusCur">?</span>/<span data-mud-bind="focusMax">?</span></small></span>
      <div class="v" data-mud-bind="focusName">?</div>
      <div class="hair"><div data-mud-bind-style="width:focusPct"></div></div></div>
    <div class="misc">
      <div class="pw" data-mud-bind-attr="data-ptier:powerTier" data-mud-bind-style="display:powerDisplay"><span data-mud-bind="powerName"></span> (<span data-mud-bind="powerCur"></span>)</div>
      <div><span data-mud-bind="standName">?</span> · Enc <span data-mud-bind="encum">?</span>%</div>
    </div>
  </div>
  <div class="rtbox rtc" data-mud-bind-style="visibility:rtVisibility">
    <span class="rtnum" data-mud-bind="rtSec"></span>
    <div class="rtcol"><div data-mud-bind-style="height:rtPct"></div></div>
    <span class="rtk">RT</span>
  </div>
</div>
]==] },
}

-- Values the widget shows verbatim: bound straight from the package, no code in between.
local DIRECT = {
  condName = "condition.name", condCur = "condition.cur", condMax = "condition.max",
  footName = "footing.name",   footCur = "footing.cur",   footMax = "footing.max",
  focusName = "focus.name",    focusCur = "focus.cur",    focusMax = "focus.max",
  standName = "standing.name", encum = "encumbrance",
}

local widgets = {}
local rtAnchor = nil   -- { total = ms, endsAt = local ms } while a Round Time is running
local tickTimer = nil

local function pushAll(keys)
  for _, id in ipairs(widgets) do setBoundValues(id, keys) end
end

-- Computed keys: fill percentages, tier colours, and held power (whose key is absent when none is held).
local function pct(cur, max)
  if not max or max <= 0 or not cur then return "0%" end
  local p = cur / max * 100
  if p < 0 then p = 0 elseif p > 100 then p = 100 end
  return p .. "%"
end

local function vitalsKeys(v)
  local k = {}
  local meters = { cond = v.condition, foot = v.footing, focus = v.focus }
  for key, m in pairs(meters) do
    if m then
      k[key .. "Tier"] = m.tier
      k[key .. "Pct"] = pct(m.cur, m.max)
      k[key .. "Tip"] = tostring(m.cur) .. "/" .. tostring(m.max)
    end
  end
  if v.power then
    k.powerName = v.power.name; k.powerCur = v.power.cur; k.powerTier = v.power.tier; k.powerDisplay = ""
  else
    k.powerName = ""; k.powerCur = ""; k.powerTier = ""; k.powerDisplay = "none"
  end
  return k
end

local function rtKeys()
  if not rtAnchor then
    return { rtDisplay = "none", rtVisibility = "hidden", rtPct = "0%", rtSec = "" }
  end
  local left = rtAnchor.endsAt - getCurrentTime()
  if left <= 0 then
    rtAnchor = nil
    return rtKeys()
  end
  local tenths = math.floor(left / 100)
  local sec = math.floor(tenths / 10)
  local dec = tenths % 10
  return {
    rtDisplay = "", rtVisibility = "visible",
    rtPct = (left / rtAnchor.total * 100) .. "%",
    rtSec = sec .. "." .. dec .. "s",
  }
end

-- Cadence-agnostic: every push re-anchors remaining = clears_at_ms - now_ms; the timer drains it locally.
local function onRoundTime(p)
  if not p or not p.clears_at_ms or p.clears_at_ms == 0 then rtAnchor = nil; return end
  local left = p.clears_at_ms - (p.now_ms or 0)
  if left <= 0 then rtAnchor = nil; return end
  local now = getCurrentTime()
  local total = left
  if rtAnchor and rtAnchor.endsAt > now and rtAnchor.total > left then total = rtAnchor.total end
  rtAnchor = { total = total, endsAt = now + left }
end

local function startTick()
  if tickTimer and tickTimer ~= "" then return end
  tickTimer = addTimer(100, function()
    if rtAnchor then pushAll(rtKeys()) end
  end, true)
end

function init()
  widgets = {}
  for _, v in ipairs(VARIANTS) do
    local id = createWidget({
      type = "html",
      name = "status-" .. v.key,
      title = "Status " .. v.key .. " - " .. v.name,
      position = { x = v.x, y = v.y },
      size = { width = v.width, height = v.height },
    })
    setWidgetProperty(id, "content", v.content)
    for key, path in pairs(DIRECT) do bindWidgetGMCP(id, key, "Char.Vitals", path) end
    widgets[#widgets + 1] = id
  end

  onGMCPUpdate("Char.Vitals", function(v) pushAll(vitalsKeys(v)) end)
  onGMCPUpdate("Char.RoundTime", function(p) onRoundTime(p); pushAll(rtKeys()) end)

  local v = getGMCPData("Char.Vitals")
  if v then pushAll(vitalsKeys(v)) else pushAll(vitalsKeys({})) end
  onRoundTime(getGMCPData("Char.RoundTime"))
  pushAll(rtKeys())
  startTick()
  print("[textdungeon-hud-prototype] mounted Status variants A, B, C")
end

function onConnect()
  startTick()   -- timers refuse to start while disconnected
end

function onDisconnect()
  tickTimer = nil
  rtAnchor = nil
  pushAll(rtKeys())
end
