// node tools/build.js [--check] [--install [dir]]
//
// Inlines lib/*.lua and src/widgets/*.html into src/textdungeon-hud.lua and
// writes the single-file plugin textdungeon-hud.lua at the repo root (ADR 0001).
// Source files are never rewritten.
//
//   --check          build to memory and fail if the committed root file differs
//   --install [dir]  also copy the output into MudForge's watched plugins folder:
//                    <dir>, else $MUDFORGE_PLUGINS_DIR, else %APPDATA%/com.mudforge.app/plugins
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const OUT = path.join(ROOT, "textdungeon-hud.lua");

// Fixed dependency order: a lib may only require() libs listed before it.
const LIBS = ["countdown", "status"];
const WIDGETS = ["status", "effects", "slots"];

const read = rel => fs.readFileSync(path.join(ROOT, rel), "utf8").replace(/\r\n/g, "\n");

function longString(s, what) {
  if (s.includes("]==]")) throw new Error(what + " contains ']==]'");
  return "[==[\n" + s + "]==]";
}

function build() {
  const src = read("src/textdungeon-hud.lua");
  // MudForge reads plugin metadata from the top-level `plugin = { ... }` block;
  // hoist it above the inlined libs so it stays at the head of the file.
  const m = /^plugin\s*=\s*\{[\s\S]*?^\}[ \t]*\n/m.exec(src);
  if (!m) throw new Error("src/textdungeon-hud.lua: no top-level `plugin = { ... }` block");
  const pluginBlock = m[0];
  const rest = src.slice(0, m.index) + src.slice(m.index + m[0].length);

  const out = [];
  out.push("-- BUILT FILE - do not edit. Generated by tools/build.js from src/ and lib/;");
  out.push("-- edit those and run `npm run build`. `npm test` fails while this file is stale.");
  out.push("");
  out.push(pluginBlock.trimEnd());
  out.push("");
  out.push("local __libs = {}");
  out.push("local function __require(name)");
  out.push("  local m = __libs[name]");
  out.push('  if m == nil then error("module \'" .. name .. "\' not found") end');
  out.push("  return m");
  out.push("end");
  for (const name of LIBS) {
    out.push("");
    out.push("-- lib/" + name + ".lua");
    out.push('__libs["' + name + '"] = (function()');
    out.push("  local require = __require");
    out.push(read("lib/" + name + ".lua").trimEnd());
    out.push("end)()");
  }
  const css = read("src/widgets/shared.css").trimEnd();
  out.push("");
  out.push("-- src/widgets/*.html, each with shared.css inlined");
  out.push('__libs["widgets"] = {');
  for (const name of WIDGETS) {
    const html = "<style>\n" + css + "\n</style>\n" + read("src/widgets/" + name + ".html");
    out.push('  ["' + name + '"] = ' + longString(html, "src/widgets/" + name + ".html") + ",");
  }
  out.push("}");
  out.push("");
  out.push("local require = __require");
  out.push("");
  out.push("-- src/textdungeon-hud.lua");
  out.push(rest.trim());
  out.push("");
  return out.join("\n");
}

const args = process.argv.slice(2);
const built = build();

if (args.includes("--check")) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8").replace(/\r\n/g, "\n") : null;
  if (current !== built) {
    console.error("stale build: textdungeon-hud.lua differs from src/ + lib/ - run `npm run build` and commit");
    process.exit(1);
  }
  console.log("build up to date");
  process.exit(0);
}

fs.writeFileSync(OUT, built);
console.log("wrote " + path.relative(ROOT, OUT) + " (" + built.length + " bytes)");

const i = args.indexOf("--install");
if (i !== -1) {
  const next = args[i + 1];
  const dir = (next && !next.startsWith("--") && next) ||
    process.env.MUDFORGE_PLUGINS_DIR ||
    (process.env.APPDATA && path.join(process.env.APPDATA, "com.mudforge.app", "plugins"));
  if (!dir || !fs.existsSync(dir)) {
    console.error("--install: plugins folder not found (" + (dir || "no dir given") + "); pass --install <dir> or set MUDFORGE_PLUGINS_DIR");
    process.exit(1);
  }
  const dest = path.join(dir, path.basename(OUT));
  fs.copyFileSync(OUT, dest);
  console.log("copied to " + dest);
}
